//------------------------------------------------------------------------------
// <auto-generated />
//
// This file was automatically generated by SWIG (http://www.swig.org).
// Version 3.0.12
//
// Do not make changes to this file unless you know what you are doing--modify
// the SWIG interface file instead.
//------------------------------------------------------------------------------


class IsarMaincsPINVOKE {

  protected class SWIGExceptionHelper {

    public delegate void ExceptionDelegate(string message);
    public delegate void ExceptionArgumentDelegate(string message, string paramName);

    static ExceptionDelegate applicationDelegate = new ExceptionDelegate(SetPendingApplicationException);
    static ExceptionDelegate arithmeticDelegate = new ExceptionDelegate(SetPendingArithmeticException);
    static ExceptionDelegate divideByZeroDelegate = new ExceptionDelegate(SetPendingDivideByZeroException);
    static ExceptionDelegate indexOutOfRangeDelegate = new ExceptionDelegate(SetPendingIndexOutOfRangeException);
    static ExceptionDelegate invalidCastDelegate = new ExceptionDelegate(SetPendingInvalidCastException);
    static ExceptionDelegate invalidOperationDelegate = new ExceptionDelegate(SetPendingInvalidOperationException);
    static ExceptionDelegate ioDelegate = new ExceptionDelegate(SetPendingIOException);
    static ExceptionDelegate nullReferenceDelegate = new ExceptionDelegate(SetPendingNullReferenceException);
    static ExceptionDelegate outOfMemoryDelegate = new ExceptionDelegate(SetPendingOutOfMemoryException);
    static ExceptionDelegate overflowDelegate = new ExceptionDelegate(SetPendingOverflowException);
    static ExceptionDelegate systemDelegate = new ExceptionDelegate(SetPendingSystemException);

    static ExceptionArgumentDelegate argumentDelegate = new ExceptionArgumentDelegate(SetPendingArgumentException);
    static ExceptionArgumentDelegate argumentNullDelegate = new ExceptionArgumentDelegate(SetPendingArgumentNullException);
    static ExceptionArgumentDelegate argumentOutOfRangeDelegate = new ExceptionArgumentDelegate(SetPendingArgumentOutOfRangeException);

    [global::System.Runtime.InteropServices.DllImport("codegen/dll/IsarMain/IsarMain.dll", EntryPoint="SWIGRegisterExceptionCallbacks_IsarMaincs")]
    public static extern void SWIGRegisterExceptionCallbacks_IsarMaincs(
                                ExceptionDelegate applicationDelegate,
                                ExceptionDelegate arithmeticDelegate,
                                ExceptionDelegate divideByZeroDelegate, 
                                ExceptionDelegate indexOutOfRangeDelegate, 
                                ExceptionDelegate invalidCastDelegate,
                                ExceptionDelegate invalidOperationDelegate,
                                ExceptionDelegate ioDelegate,
                                ExceptionDelegate nullReferenceDelegate,
                                ExceptionDelegate outOfMemoryDelegate, 
                                ExceptionDelegate overflowDelegate, 
                                ExceptionDelegate systemExceptionDelegate);

    [global::System.Runtime.InteropServices.DllImport("codegen/dll/IsarMain/IsarMain.dll", EntryPoint="SWIGRegisterExceptionArgumentCallbacks_IsarMaincs")]
    public static extern void SWIGRegisterExceptionCallbacksArgument_IsarMaincs(
                                ExceptionArgumentDelegate argumentDelegate,
                                ExceptionArgumentDelegate argumentNullDelegate,
                                ExceptionArgumentDelegate argumentOutOfRangeDelegate);

    static void SetPendingApplicationException(string message) {
      SWIGPendingException.Set(new global::System.ApplicationException(message, SWIGPendingException.Retrieve()));
    }
    static void SetPendingArithmeticException(string message) {
      SWIGPendingException.Set(new global::System.ArithmeticException(message, SWIGPendingException.Retrieve()));
    }
    static void SetPendingDivideByZeroException(string message) {
      SWIGPendingException.Set(new global::System.DivideByZeroException(message, SWIGPendingException.Retrieve()));
    }
    static void SetPendingIndexOutOfRangeException(string message) {
      SWIGPendingException.Set(new global::System.IndexOutOfRangeException(message, SWIGPendingException.Retrieve()));
    }
    static void SetPendingInvalidCastException(string message) {
      SWIGPendingException.Set(new global::System.InvalidCastException(message, SWIGPendingException.Retrieve()));
    }
    static void SetPendingInvalidOperationException(string message) {
      SWIGPendingException.Set(new global::System.InvalidOperationException(message, SWIGPendingException.Retrieve()));
    }
    static void SetPendingIOException(string message) {
      SWIGPendingException.Set(new global::System.IO.IOException(message, SWIGPendingException.Retrieve()));
    }
    static void SetPendingNullReferenceException(string message) {
      SWIGPendingException.Set(new global::System.NullReferenceException(message, SWIGPendingException.Retrieve()));
    }
    static void SetPendingOutOfMemoryException(string message) {
      SWIGPendingException.Set(new global::System.OutOfMemoryException(message, SWIGPendingException.Retrieve()));
    }
    static void SetPendingOverflowException(string message) {
      SWIGPendingException.Set(new global::System.OverflowException(message, SWIGPendingException.Retrieve()));
    }
    static void SetPendingSystemException(string message) {
      SWIGPendingException.Set(new global::System.SystemException(message, SWIGPendingException.Retrieve()));
    }

    static void SetPendingArgumentException(string message, string paramName) {
      SWIGPendingException.Set(new global::System.ArgumentException(message, paramName, SWIGPendingException.Retrieve()));
    }
    static void SetPendingArgumentNullException(string message, string paramName) {
      global::System.Exception e = SWIGPendingException.Retrieve();
      if (e != null) message = message + " Inner Exception: " + e.Message;
      SWIGPendingException.Set(new global::System.ArgumentNullException(paramName, message));
    }
    static void SetPendingArgumentOutOfRangeException(string message, string paramName) {
      global::System.Exception e = SWIGPendingException.Retrieve();
      if (e != null) message = message + " Inner Exception: " + e.Message;
      SWIGPendingException.Set(new global::System.ArgumentOutOfRangeException(paramName, message));
    }

    static SWIGExceptionHelper() {
      SWIGRegisterExceptionCallbacks_IsarMaincs(
                                applicationDelegate,
                                arithmeticDelegate,
                                divideByZeroDelegate,
                                indexOutOfRangeDelegate,
                                invalidCastDelegate,
                                invalidOperationDelegate,
                                ioDelegate,
                                nullReferenceDelegate,
                                outOfMemoryDelegate,
                                overflowDelegate,
                                systemDelegate);

      SWIGRegisterExceptionCallbacksArgument_IsarMaincs(
                                argumentDelegate,
                                argumentNullDelegate,
                                argumentOutOfRangeDelegate);
    }
  }

  protected static SWIGExceptionHelper swigExceptionHelper = new SWIGExceptionHelper();

  public class SWIGPendingException {
    [global::System.ThreadStatic]
    private static global::System.Exception pendingException = null;
    private static int numExceptionsPending = 0;

    public static bool Pending {
      get {
        bool pending = false;
        if (numExceptionsPending > 0)
          if (pendingException != null)
            pending = true;
        return pending;
      } 
    }

    public static void Set(global::System.Exception e) {
      if (pendingException != null)
        throw new global::System.ApplicationException("FATAL: An earlier pending exception from unmanaged code was missed and thus not thrown (" + pendingException.ToString() + ")", e);
      pendingException = e;
      lock(typeof(IsarMaincsPINVOKE)) {
        numExceptionsPending++;
      }
    }

    public static global::System.Exception Retrieve() {
      global::System.Exception e = null;
      if (numExceptionsPending > 0) {
        if (pendingException != null) {
          e = pendingException;
          pendingException = null;
          lock(typeof(IsarMaincsPINVOKE)) {
            numExceptionsPending--;
          }
        }
      }
      return e;
    }
  }


  protected class SWIGStringHelper {

    public delegate string SWIGStringDelegate(string message);
    static SWIGStringDelegate stringDelegate = new SWIGStringDelegate(CreateString);

    [global::System.Runtime.InteropServices.DllImport("codegen/dll/IsarMain/IsarMain.dll", EntryPoint="SWIGRegisterStringCallback_IsarMaincs")]
    public static extern void SWIGRegisterStringCallback_IsarMaincs(SWIGStringDelegate stringDelegate);

    static string CreateString(string cString) {
      return cString;
    }

    static SWIGStringHelper() {
      SWIGRegisterStringCallback_IsarMaincs(stringDelegate);
    }
  }

  static protected SWIGStringHelper swigStringHelper = new SWIGStringHelper();


  static IsarMaincsPINVOKE() {
  }


  [global::System.Runtime.InteropServices.DllImport("codegen/dll/IsarMain/IsarMain.dll", EntryPoint="CSharp_new_doubleArray")]
  public static extern global::System.IntPtr new_doubleArray(int jarg1);

  [global::System.Runtime.InteropServices.DllImport("codegen/dll/IsarMain/IsarMain.dll", EntryPoint="CSharp_delete_doubleArray")]
  public static extern void delete_doubleArray(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("codegen/dll/IsarMain/IsarMain.dll", EntryPoint="CSharp_doubleArray_getitem")]
  public static extern double doubleArray_getitem(global::System.Runtime.InteropServices.HandleRef jarg1, int jarg2);

  [global::System.Runtime.InteropServices.DllImport("codegen/dll/IsarMain/IsarMain.dll", EntryPoint="CSharp_doubleArray_setitem")]
  public static extern void doubleArray_setitem(global::System.Runtime.InteropServices.HandleRef jarg1, int jarg2, double jarg3);

  [global::System.Runtime.InteropServices.DllImport("codegen/dll/IsarMain/IsarMain.dll", EntryPoint="CSharp_doubleArray_cast")]
  public static extern global::System.IntPtr doubleArray_cast(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("codegen/dll/IsarMain/IsarMain.dll", EntryPoint="CSharp_doubleArray_frompointer")]
  public static extern global::System.IntPtr doubleArray_frompointer(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("codegen/dll/IsarMain/IsarMain.dll", EntryPoint="CSharp_new_intArray")]
  public static extern global::System.IntPtr new_intArray(int jarg1);

  [global::System.Runtime.InteropServices.DllImport("codegen/dll/IsarMain/IsarMain.dll", EntryPoint="CSharp_delete_intArray")]
  public static extern void delete_intArray(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("codegen/dll/IsarMain/IsarMain.dll", EntryPoint="CSharp_intArray_getitem")]
  public static extern int intArray_getitem(global::System.Runtime.InteropServices.HandleRef jarg1, int jarg2);

  [global::System.Runtime.InteropServices.DllImport("codegen/dll/IsarMain/IsarMain.dll", EntryPoint="CSharp_intArray_setitem")]
  public static extern void intArray_setitem(global::System.Runtime.InteropServices.HandleRef jarg1, int jarg2, int jarg3);

  [global::System.Runtime.InteropServices.DllImport("codegen/dll/IsarMain/IsarMain.dll", EntryPoint="CSharp_intArray_cast")]
  public static extern global::System.IntPtr intArray_cast(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("codegen/dll/IsarMain/IsarMain.dll", EntryPoint="CSharp_intArray_frompointer")]
  public static extern global::System.IntPtr intArray_frompointer(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("codegen/dll/IsarMain/IsarMain.dll", EntryPoint="CSharp_emxArray_creal_T_data_set")]
  public static extern void emxArray_creal_T_data_set(global::System.Runtime.InteropServices.HandleRef jarg1, global::System.Runtime.InteropServices.HandleRef jarg2);

  [global::System.Runtime.InteropServices.DllImport("codegen/dll/IsarMain/IsarMain.dll", EntryPoint="CSharp_emxArray_creal_T_data_get")]
  public static extern global::System.IntPtr emxArray_creal_T_data_get(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("codegen/dll/IsarMain/IsarMain.dll", EntryPoint="CSharp_emxArray_creal_T_size_set")]
  public static extern void emxArray_creal_T_size_set(global::System.Runtime.InteropServices.HandleRef jarg1, global::System.Runtime.InteropServices.HandleRef jarg2);

  [global::System.Runtime.InteropServices.DllImport("codegen/dll/IsarMain/IsarMain.dll", EntryPoint="CSharp_emxArray_creal_T_size_get")]
  public static extern global::System.IntPtr emxArray_creal_T_size_get(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("codegen/dll/IsarMain/IsarMain.dll", EntryPoint="CSharp_emxArray_creal_T_allocatedSize_set")]
  public static extern void emxArray_creal_T_allocatedSize_set(global::System.Runtime.InteropServices.HandleRef jarg1, global::System.Runtime.InteropServices.HandleRef jarg2);

  [global::System.Runtime.InteropServices.DllImport("codegen/dll/IsarMain/IsarMain.dll", EntryPoint="CSharp_emxArray_creal_T_allocatedSize_get")]
  public static extern global::System.IntPtr emxArray_creal_T_allocatedSize_get(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("codegen/dll/IsarMain/IsarMain.dll", EntryPoint="CSharp_emxArray_creal_T_numDimensions_set")]
  public static extern void emxArray_creal_T_numDimensions_set(global::System.Runtime.InteropServices.HandleRef jarg1, global::System.Runtime.InteropServices.HandleRef jarg2);

  [global::System.Runtime.InteropServices.DllImport("codegen/dll/IsarMain/IsarMain.dll", EntryPoint="CSharp_emxArray_creal_T_numDimensions_get")]
  public static extern global::System.IntPtr emxArray_creal_T_numDimensions_get(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("codegen/dll/IsarMain/IsarMain.dll", EntryPoint="CSharp_emxArray_creal_T_canFreeData_set")]
  public static extern void emxArray_creal_T_canFreeData_set(global::System.Runtime.InteropServices.HandleRef jarg1, global::System.Runtime.InteropServices.HandleRef jarg2);

  [global::System.Runtime.InteropServices.DllImport("codegen/dll/IsarMain/IsarMain.dll", EntryPoint="CSharp_emxArray_creal_T_canFreeData_get")]
  public static extern global::System.IntPtr emxArray_creal_T_canFreeData_get(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("codegen/dll/IsarMain/IsarMain.dll", EntryPoint="CSharp_new_emxArray_creal_T")]
  public static extern global::System.IntPtr new_emxArray_creal_T();

  [global::System.Runtime.InteropServices.DllImport("codegen/dll/IsarMain/IsarMain.dll", EntryPoint="CSharp_delete_emxArray_creal_T")]
  public static extern void delete_emxArray_creal_T(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("codegen/dll/IsarMain/IsarMain.dll", EntryPoint="CSharp_emxArray_int32_T_data_set")]
  public static extern void emxArray_int32_T_data_set(global::System.Runtime.InteropServices.HandleRef jarg1, global::System.Runtime.InteropServices.HandleRef jarg2);

  [global::System.Runtime.InteropServices.DllImport("codegen/dll/IsarMain/IsarMain.dll", EntryPoint="CSharp_emxArray_int32_T_data_get")]
  public static extern global::System.IntPtr emxArray_int32_T_data_get(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("codegen/dll/IsarMain/IsarMain.dll", EntryPoint="CSharp_emxArray_int32_T_size_set")]
  public static extern void emxArray_int32_T_size_set(global::System.Runtime.InteropServices.HandleRef jarg1, global::System.Runtime.InteropServices.HandleRef jarg2);

  [global::System.Runtime.InteropServices.DllImport("codegen/dll/IsarMain/IsarMain.dll", EntryPoint="CSharp_emxArray_int32_T_size_get")]
  public static extern global::System.IntPtr emxArray_int32_T_size_get(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("codegen/dll/IsarMain/IsarMain.dll", EntryPoint="CSharp_emxArray_int32_T_allocatedSize_set")]
  public static extern void emxArray_int32_T_allocatedSize_set(global::System.Runtime.InteropServices.HandleRef jarg1, global::System.Runtime.InteropServices.HandleRef jarg2);

  [global::System.Runtime.InteropServices.DllImport("codegen/dll/IsarMain/IsarMain.dll", EntryPoint="CSharp_emxArray_int32_T_allocatedSize_get")]
  public static extern global::System.IntPtr emxArray_int32_T_allocatedSize_get(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("codegen/dll/IsarMain/IsarMain.dll", EntryPoint="CSharp_emxArray_int32_T_numDimensions_set")]
  public static extern void emxArray_int32_T_numDimensions_set(global::System.Runtime.InteropServices.HandleRef jarg1, global::System.Runtime.InteropServices.HandleRef jarg2);

  [global::System.Runtime.InteropServices.DllImport("codegen/dll/IsarMain/IsarMain.dll", EntryPoint="CSharp_emxArray_int32_T_numDimensions_get")]
  public static extern global::System.IntPtr emxArray_int32_T_numDimensions_get(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("codegen/dll/IsarMain/IsarMain.dll", EntryPoint="CSharp_emxArray_int32_T_canFreeData_set")]
  public static extern void emxArray_int32_T_canFreeData_set(global::System.Runtime.InteropServices.HandleRef jarg1, global::System.Runtime.InteropServices.HandleRef jarg2);

  [global::System.Runtime.InteropServices.DllImport("codegen/dll/IsarMain/IsarMain.dll", EntryPoint="CSharp_emxArray_int32_T_canFreeData_get")]
  public static extern global::System.IntPtr emxArray_int32_T_canFreeData_get(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("codegen/dll/IsarMain/IsarMain.dll", EntryPoint="CSharp_new_emxArray_int32_T")]
  public static extern global::System.IntPtr new_emxArray_int32_T();

  [global::System.Runtime.InteropServices.DllImport("codegen/dll/IsarMain/IsarMain.dll", EntryPoint="CSharp_delete_emxArray_int32_T")]
  public static extern void delete_emxArray_int32_T(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("codegen/dll/IsarMain/IsarMain.dll", EntryPoint="CSharp_emxArray_int8_T_data_set")]
  public static extern void emxArray_int8_T_data_set(global::System.Runtime.InteropServices.HandleRef jarg1, global::System.Runtime.InteropServices.HandleRef jarg2);

  [global::System.Runtime.InteropServices.DllImport("codegen/dll/IsarMain/IsarMain.dll", EntryPoint="CSharp_emxArray_int8_T_data_get")]
  public static extern global::System.IntPtr emxArray_int8_T_data_get(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("codegen/dll/IsarMain/IsarMain.dll", EntryPoint="CSharp_emxArray_int8_T_size_set")]
  public static extern void emxArray_int8_T_size_set(global::System.Runtime.InteropServices.HandleRef jarg1, global::System.Runtime.InteropServices.HandleRef jarg2);

  [global::System.Runtime.InteropServices.DllImport("codegen/dll/IsarMain/IsarMain.dll", EntryPoint="CSharp_emxArray_int8_T_size_get")]
  public static extern global::System.IntPtr emxArray_int8_T_size_get(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("codegen/dll/IsarMain/IsarMain.dll", EntryPoint="CSharp_emxArray_int8_T_allocatedSize_set")]
  public static extern void emxArray_int8_T_allocatedSize_set(global::System.Runtime.InteropServices.HandleRef jarg1, global::System.Runtime.InteropServices.HandleRef jarg2);

  [global::System.Runtime.InteropServices.DllImport("codegen/dll/IsarMain/IsarMain.dll", EntryPoint="CSharp_emxArray_int8_T_allocatedSize_get")]
  public static extern global::System.IntPtr emxArray_int8_T_allocatedSize_get(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("codegen/dll/IsarMain/IsarMain.dll", EntryPoint="CSharp_emxArray_int8_T_numDimensions_set")]
  public static extern void emxArray_int8_T_numDimensions_set(global::System.Runtime.InteropServices.HandleRef jarg1, global::System.Runtime.InteropServices.HandleRef jarg2);

  [global::System.Runtime.InteropServices.DllImport("codegen/dll/IsarMain/IsarMain.dll", EntryPoint="CSharp_emxArray_int8_T_numDimensions_get")]
  public static extern global::System.IntPtr emxArray_int8_T_numDimensions_get(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("codegen/dll/IsarMain/IsarMain.dll", EntryPoint="CSharp_emxArray_int8_T_canFreeData_set")]
  public static extern void emxArray_int8_T_canFreeData_set(global::System.Runtime.InteropServices.HandleRef jarg1, global::System.Runtime.InteropServices.HandleRef jarg2);

  [global::System.Runtime.InteropServices.DllImport("codegen/dll/IsarMain/IsarMain.dll", EntryPoint="CSharp_emxArray_int8_T_canFreeData_get")]
  public static extern global::System.IntPtr emxArray_int8_T_canFreeData_get(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("codegen/dll/IsarMain/IsarMain.dll", EntryPoint="CSharp_new_emxArray_int8_T")]
  public static extern global::System.IntPtr new_emxArray_int8_T();

  [global::System.Runtime.InteropServices.DllImport("codegen/dll/IsarMain/IsarMain.dll", EntryPoint="CSharp_delete_emxArray_int8_T")]
  public static extern void delete_emxArray_int8_T(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("codegen/dll/IsarMain/IsarMain.dll", EntryPoint="CSharp_emxArray_real_T_data_set")]
  public static extern void emxArray_real_T_data_set(global::System.Runtime.InteropServices.HandleRef jarg1, global::System.Runtime.InteropServices.HandleRef jarg2);

  [global::System.Runtime.InteropServices.DllImport("codegen/dll/IsarMain/IsarMain.dll", EntryPoint="CSharp_emxArray_real_T_data_get")]
  public static extern global::System.IntPtr emxArray_real_T_data_get(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("codegen/dll/IsarMain/IsarMain.dll", EntryPoint="CSharp_emxArray_real_T_size_set")]
  public static extern void emxArray_real_T_size_set(global::System.Runtime.InteropServices.HandleRef jarg1, global::System.Runtime.InteropServices.HandleRef jarg2);

  [global::System.Runtime.InteropServices.DllImport("codegen/dll/IsarMain/IsarMain.dll", EntryPoint="CSharp_emxArray_real_T_size_get")]
  public static extern global::System.IntPtr emxArray_real_T_size_get(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("codegen/dll/IsarMain/IsarMain.dll", EntryPoint="CSharp_emxArray_real_T_allocatedSize_set")]
  public static extern void emxArray_real_T_allocatedSize_set(global::System.Runtime.InteropServices.HandleRef jarg1, global::System.Runtime.InteropServices.HandleRef jarg2);

  [global::System.Runtime.InteropServices.DllImport("codegen/dll/IsarMain/IsarMain.dll", EntryPoint="CSharp_emxArray_real_T_allocatedSize_get")]
  public static extern global::System.IntPtr emxArray_real_T_allocatedSize_get(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("codegen/dll/IsarMain/IsarMain.dll", EntryPoint="CSharp_emxArray_real_T_numDimensions_set")]
  public static extern void emxArray_real_T_numDimensions_set(global::System.Runtime.InteropServices.HandleRef jarg1, global::System.Runtime.InteropServices.HandleRef jarg2);

  [global::System.Runtime.InteropServices.DllImport("codegen/dll/IsarMain/IsarMain.dll", EntryPoint="CSharp_emxArray_real_T_numDimensions_get")]
  public static extern global::System.IntPtr emxArray_real_T_numDimensions_get(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("codegen/dll/IsarMain/IsarMain.dll", EntryPoint="CSharp_emxArray_real_T_canFreeData_set")]
  public static extern void emxArray_real_T_canFreeData_set(global::System.Runtime.InteropServices.HandleRef jarg1, global::System.Runtime.InteropServices.HandleRef jarg2);

  [global::System.Runtime.InteropServices.DllImport("codegen/dll/IsarMain/IsarMain.dll", EntryPoint="CSharp_emxArray_real_T_canFreeData_get")]
  public static extern global::System.IntPtr emxArray_real_T_canFreeData_get(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("codegen/dll/IsarMain/IsarMain.dll", EntryPoint="CSharp_delete_emxArray_real_T")]
  public static extern void delete_emxArray_real_T(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("codegen/dll/IsarMain/IsarMain.dll", EntryPoint="CSharp_new_emxArray_real_T")]
  public static extern global::System.IntPtr new_emxArray_real_T();

  [global::System.Runtime.InteropServices.DllImport("codegen/dll/IsarMain/IsarMain.dll", EntryPoint="CSharp_rtBoundsCheckInfo_iFirst_set")]
  public static extern void rtBoundsCheckInfo_iFirst_set(global::System.Runtime.InteropServices.HandleRef jarg1, global::System.Runtime.InteropServices.HandleRef jarg2);

  [global::System.Runtime.InteropServices.DllImport("codegen/dll/IsarMain/IsarMain.dll", EntryPoint="CSharp_rtBoundsCheckInfo_iFirst_get")]
  public static extern global::System.IntPtr rtBoundsCheckInfo_iFirst_get(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("codegen/dll/IsarMain/IsarMain.dll", EntryPoint="CSharp_rtBoundsCheckInfo_iLast_set")]
  public static extern void rtBoundsCheckInfo_iLast_set(global::System.Runtime.InteropServices.HandleRef jarg1, global::System.Runtime.InteropServices.HandleRef jarg2);

  [global::System.Runtime.InteropServices.DllImport("codegen/dll/IsarMain/IsarMain.dll", EntryPoint="CSharp_rtBoundsCheckInfo_iLast_get")]
  public static extern global::System.IntPtr rtBoundsCheckInfo_iLast_get(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("codegen/dll/IsarMain/IsarMain.dll", EntryPoint="CSharp_rtBoundsCheckInfo_lineNo_set")]
  public static extern void rtBoundsCheckInfo_lineNo_set(global::System.Runtime.InteropServices.HandleRef jarg1, global::System.Runtime.InteropServices.HandleRef jarg2);

  [global::System.Runtime.InteropServices.DllImport("codegen/dll/IsarMain/IsarMain.dll", EntryPoint="CSharp_rtBoundsCheckInfo_lineNo_get")]
  public static extern global::System.IntPtr rtBoundsCheckInfo_lineNo_get(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("codegen/dll/IsarMain/IsarMain.dll", EntryPoint="CSharp_rtBoundsCheckInfo_colNo_set")]
  public static extern void rtBoundsCheckInfo_colNo_set(global::System.Runtime.InteropServices.HandleRef jarg1, global::System.Runtime.InteropServices.HandleRef jarg2);

  [global::System.Runtime.InteropServices.DllImport("codegen/dll/IsarMain/IsarMain.dll", EntryPoint="CSharp_rtBoundsCheckInfo_colNo_get")]
  public static extern global::System.IntPtr rtBoundsCheckInfo_colNo_get(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("codegen/dll/IsarMain/IsarMain.dll", EntryPoint="CSharp_rtBoundsCheckInfo_aName_set")]
  public static extern void rtBoundsCheckInfo_aName_set(global::System.Runtime.InteropServices.HandleRef jarg1, string jarg2);

  [global::System.Runtime.InteropServices.DllImport("codegen/dll/IsarMain/IsarMain.dll", EntryPoint="CSharp_rtBoundsCheckInfo_aName_get")]
  public static extern string rtBoundsCheckInfo_aName_get(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("codegen/dll/IsarMain/IsarMain.dll", EntryPoint="CSharp_rtBoundsCheckInfo_fName_set")]
  public static extern void rtBoundsCheckInfo_fName_set(global::System.Runtime.InteropServices.HandleRef jarg1, string jarg2);

  [global::System.Runtime.InteropServices.DllImport("codegen/dll/IsarMain/IsarMain.dll", EntryPoint="CSharp_rtBoundsCheckInfo_fName_get")]
  public static extern string rtBoundsCheckInfo_fName_get(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("codegen/dll/IsarMain/IsarMain.dll", EntryPoint="CSharp_rtBoundsCheckInfo_pName_set")]
  public static extern void rtBoundsCheckInfo_pName_set(global::System.Runtime.InteropServices.HandleRef jarg1, string jarg2);

  [global::System.Runtime.InteropServices.DllImport("codegen/dll/IsarMain/IsarMain.dll", EntryPoint="CSharp_rtBoundsCheckInfo_pName_get")]
  public static extern string rtBoundsCheckInfo_pName_get(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("codegen/dll/IsarMain/IsarMain.dll", EntryPoint="CSharp_rtBoundsCheckInfo_checkKind_set")]
  public static extern void rtBoundsCheckInfo_checkKind_set(global::System.Runtime.InteropServices.HandleRef jarg1, global::System.Runtime.InteropServices.HandleRef jarg2);

  [global::System.Runtime.InteropServices.DllImport("codegen/dll/IsarMain/IsarMain.dll", EntryPoint="CSharp_rtBoundsCheckInfo_checkKind_get")]
  public static extern global::System.IntPtr rtBoundsCheckInfo_checkKind_get(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("codegen/dll/IsarMain/IsarMain.dll", EntryPoint="CSharp_new_rtBoundsCheckInfo")]
  public static extern global::System.IntPtr new_rtBoundsCheckInfo();

  [global::System.Runtime.InteropServices.DllImport("codegen/dll/IsarMain/IsarMain.dll", EntryPoint="CSharp_delete_rtBoundsCheckInfo")]
  public static extern void delete_rtBoundsCheckInfo(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("codegen/dll/IsarMain/IsarMain.dll", EntryPoint="CSharp_rtDoubleCheckInfo_lineNo_set")]
  public static extern void rtDoubleCheckInfo_lineNo_set(global::System.Runtime.InteropServices.HandleRef jarg1, global::System.Runtime.InteropServices.HandleRef jarg2);

  [global::System.Runtime.InteropServices.DllImport("codegen/dll/IsarMain/IsarMain.dll", EntryPoint="CSharp_rtDoubleCheckInfo_lineNo_get")]
  public static extern global::System.IntPtr rtDoubleCheckInfo_lineNo_get(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("codegen/dll/IsarMain/IsarMain.dll", EntryPoint="CSharp_rtDoubleCheckInfo_colNo_set")]
  public static extern void rtDoubleCheckInfo_colNo_set(global::System.Runtime.InteropServices.HandleRef jarg1, global::System.Runtime.InteropServices.HandleRef jarg2);

  [global::System.Runtime.InteropServices.DllImport("codegen/dll/IsarMain/IsarMain.dll", EntryPoint="CSharp_rtDoubleCheckInfo_colNo_get")]
  public static extern global::System.IntPtr rtDoubleCheckInfo_colNo_get(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("codegen/dll/IsarMain/IsarMain.dll", EntryPoint="CSharp_rtDoubleCheckInfo_fName_set")]
  public static extern void rtDoubleCheckInfo_fName_set(global::System.Runtime.InteropServices.HandleRef jarg1, string jarg2);

  [global::System.Runtime.InteropServices.DllImport("codegen/dll/IsarMain/IsarMain.dll", EntryPoint="CSharp_rtDoubleCheckInfo_fName_get")]
  public static extern string rtDoubleCheckInfo_fName_get(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("codegen/dll/IsarMain/IsarMain.dll", EntryPoint="CSharp_rtDoubleCheckInfo_pName_set")]
  public static extern void rtDoubleCheckInfo_pName_set(global::System.Runtime.InteropServices.HandleRef jarg1, string jarg2);

  [global::System.Runtime.InteropServices.DllImport("codegen/dll/IsarMain/IsarMain.dll", EntryPoint="CSharp_rtDoubleCheckInfo_pName_get")]
  public static extern string rtDoubleCheckInfo_pName_get(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("codegen/dll/IsarMain/IsarMain.dll", EntryPoint="CSharp_rtDoubleCheckInfo_checkKind_set")]
  public static extern void rtDoubleCheckInfo_checkKind_set(global::System.Runtime.InteropServices.HandleRef jarg1, global::System.Runtime.InteropServices.HandleRef jarg2);

  [global::System.Runtime.InteropServices.DllImport("codegen/dll/IsarMain/IsarMain.dll", EntryPoint="CSharp_rtDoubleCheckInfo_checkKind_get")]
  public static extern global::System.IntPtr rtDoubleCheckInfo_checkKind_get(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("codegen/dll/IsarMain/IsarMain.dll", EntryPoint="CSharp_new_rtDoubleCheckInfo")]
  public static extern global::System.IntPtr new_rtDoubleCheckInfo();

  [global::System.Runtime.InteropServices.DllImport("codegen/dll/IsarMain/IsarMain.dll", EntryPoint="CSharp_delete_rtDoubleCheckInfo")]
  public static extern void delete_rtDoubleCheckInfo(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("codegen/dll/IsarMain/IsarMain.dll", EntryPoint="CSharp_rtEqualityCheckInfo_nDims_set")]
  public static extern void rtEqualityCheckInfo_nDims_set(global::System.Runtime.InteropServices.HandleRef jarg1, global::System.Runtime.InteropServices.HandleRef jarg2);

  [global::System.Runtime.InteropServices.DllImport("codegen/dll/IsarMain/IsarMain.dll", EntryPoint="CSharp_rtEqualityCheckInfo_nDims_get")]
  public static extern global::System.IntPtr rtEqualityCheckInfo_nDims_get(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("codegen/dll/IsarMain/IsarMain.dll", EntryPoint="CSharp_rtEqualityCheckInfo_lineNo_set")]
  public static extern void rtEqualityCheckInfo_lineNo_set(global::System.Runtime.InteropServices.HandleRef jarg1, global::System.Runtime.InteropServices.HandleRef jarg2);

  [global::System.Runtime.InteropServices.DllImport("codegen/dll/IsarMain/IsarMain.dll", EntryPoint="CSharp_rtEqualityCheckInfo_lineNo_get")]
  public static extern global::System.IntPtr rtEqualityCheckInfo_lineNo_get(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("codegen/dll/IsarMain/IsarMain.dll", EntryPoint="CSharp_rtEqualityCheckInfo_colNo_set")]
  public static extern void rtEqualityCheckInfo_colNo_set(global::System.Runtime.InteropServices.HandleRef jarg1, global::System.Runtime.InteropServices.HandleRef jarg2);

  [global::System.Runtime.InteropServices.DllImport("codegen/dll/IsarMain/IsarMain.dll", EntryPoint="CSharp_rtEqualityCheckInfo_colNo_get")]
  public static extern global::System.IntPtr rtEqualityCheckInfo_colNo_get(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("codegen/dll/IsarMain/IsarMain.dll", EntryPoint="CSharp_rtEqualityCheckInfo_fName_set")]
  public static extern void rtEqualityCheckInfo_fName_set(global::System.Runtime.InteropServices.HandleRef jarg1, string jarg2);

  [global::System.Runtime.InteropServices.DllImport("codegen/dll/IsarMain/IsarMain.dll", EntryPoint="CSharp_rtEqualityCheckInfo_fName_get")]
  public static extern string rtEqualityCheckInfo_fName_get(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("codegen/dll/IsarMain/IsarMain.dll", EntryPoint="CSharp_rtEqualityCheckInfo_pName_set")]
  public static extern void rtEqualityCheckInfo_pName_set(global::System.Runtime.InteropServices.HandleRef jarg1, string jarg2);

  [global::System.Runtime.InteropServices.DllImport("codegen/dll/IsarMain/IsarMain.dll", EntryPoint="CSharp_rtEqualityCheckInfo_pName_get")]
  public static extern string rtEqualityCheckInfo_pName_get(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("codegen/dll/IsarMain/IsarMain.dll", EntryPoint="CSharp_new_rtEqualityCheckInfo")]
  public static extern global::System.IntPtr new_rtEqualityCheckInfo();

  [global::System.Runtime.InteropServices.DllImport("codegen/dll/IsarMain/IsarMain.dll", EntryPoint="CSharp_delete_rtEqualityCheckInfo")]
  public static extern void delete_rtEqualityCheckInfo(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("codegen/dll/IsarMain/IsarMain.dll", EntryPoint="CSharp_rtRunTimeErrorInfo_lineNo_set")]
  public static extern void rtRunTimeErrorInfo_lineNo_set(global::System.Runtime.InteropServices.HandleRef jarg1, global::System.Runtime.InteropServices.HandleRef jarg2);

  [global::System.Runtime.InteropServices.DllImport("codegen/dll/IsarMain/IsarMain.dll", EntryPoint="CSharp_rtRunTimeErrorInfo_lineNo_get")]
  public static extern global::System.IntPtr rtRunTimeErrorInfo_lineNo_get(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("codegen/dll/IsarMain/IsarMain.dll", EntryPoint="CSharp_rtRunTimeErrorInfo_colNo_set")]
  public static extern void rtRunTimeErrorInfo_colNo_set(global::System.Runtime.InteropServices.HandleRef jarg1, global::System.Runtime.InteropServices.HandleRef jarg2);

  [global::System.Runtime.InteropServices.DllImport("codegen/dll/IsarMain/IsarMain.dll", EntryPoint="CSharp_rtRunTimeErrorInfo_colNo_get")]
  public static extern global::System.IntPtr rtRunTimeErrorInfo_colNo_get(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("codegen/dll/IsarMain/IsarMain.dll", EntryPoint="CSharp_rtRunTimeErrorInfo_fName_set")]
  public static extern void rtRunTimeErrorInfo_fName_set(global::System.Runtime.InteropServices.HandleRef jarg1, string jarg2);

  [global::System.Runtime.InteropServices.DllImport("codegen/dll/IsarMain/IsarMain.dll", EntryPoint="CSharp_rtRunTimeErrorInfo_fName_get")]
  public static extern string rtRunTimeErrorInfo_fName_get(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("codegen/dll/IsarMain/IsarMain.dll", EntryPoint="CSharp_rtRunTimeErrorInfo_pName_set")]
  public static extern void rtRunTimeErrorInfo_pName_set(global::System.Runtime.InteropServices.HandleRef jarg1, string jarg2);

  [global::System.Runtime.InteropServices.DllImport("codegen/dll/IsarMain/IsarMain.dll", EntryPoint="CSharp_rtRunTimeErrorInfo_pName_get")]
  public static extern string rtRunTimeErrorInfo_pName_get(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("codegen/dll/IsarMain/IsarMain.dll", EntryPoint="CSharp_new_rtRunTimeErrorInfo")]
  public static extern global::System.IntPtr new_rtRunTimeErrorInfo();

  [global::System.Runtime.InteropServices.DllImport("codegen/dll/IsarMain/IsarMain.dll", EntryPoint="CSharp_delete_rtRunTimeErrorInfo")]
  public static extern void delete_rtRunTimeErrorInfo(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("codegen/dll/IsarMain/IsarMain.dll", EntryPoint="CSharp_IsarMain")]
  public static extern void IsarMain(global::System.Runtime.InteropServices.HandleRef jarg1, global::System.Runtime.InteropServices.HandleRef jarg2, global::System.Runtime.InteropServices.HandleRef jarg3, global::System.Runtime.InteropServices.HandleRef jarg4, global::System.Runtime.InteropServices.HandleRef jarg5, global::System.Runtime.InteropServices.HandleRef jarg6, global::System.Runtime.InteropServices.HandleRef jarg7, global::System.Runtime.InteropServices.HandleRef jarg8, global::System.Runtime.InteropServices.HandleRef jarg9);

  [global::System.Runtime.InteropServices.DllImport("codegen/dll/IsarMain/IsarMain.dll", EntryPoint="CSharp_emxCreateND_real_T")]
  public static extern global::System.IntPtr emxCreateND_real_T(global::System.Runtime.InteropServices.HandleRef jarg1, global::System.Runtime.InteropServices.HandleRef jarg2);

  [global::System.Runtime.InteropServices.DllImport("codegen/dll/IsarMain/IsarMain.dll", EntryPoint="CSharp_emxCreateWrapperND_real_T")]
  public static extern global::System.IntPtr emxCreateWrapperND_real_T(global::System.Runtime.InteropServices.HandleRef jarg1, global::System.Runtime.InteropServices.HandleRef jarg2, global::System.Runtime.InteropServices.HandleRef jarg3);

  [global::System.Runtime.InteropServices.DllImport("codegen/dll/IsarMain/IsarMain.dll", EntryPoint="CSharp_emxCreateWrapper_real_T")]
  public static extern global::System.IntPtr emxCreateWrapper_real_T(global::System.Runtime.InteropServices.HandleRef jarg1, global::System.Runtime.InteropServices.HandleRef jarg2, global::System.Runtime.InteropServices.HandleRef jarg3);

  [global::System.Runtime.InteropServices.DllImport("codegen/dll/IsarMain/IsarMain.dll", EntryPoint="CSharp_emxCreate_real_T")]
  public static extern global::System.IntPtr emxCreate_real_T(global::System.Runtime.InteropServices.HandleRef jarg1, global::System.Runtime.InteropServices.HandleRef jarg2);

  [global::System.Runtime.InteropServices.DllImport("codegen/dll/IsarMain/IsarMain.dll", EntryPoint="CSharp_emxDestroyArray_real_T")]
  public static extern void emxDestroyArray_real_T(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("codegen/dll/IsarMain/IsarMain.dll", EntryPoint="CSharp_emxInitArray_real_T")]
  public static extern void emxInitArray_real_T(global::System.Runtime.InteropServices.HandleRef jarg1, global::System.Runtime.InteropServices.HandleRef jarg2);

  [global::System.Runtime.InteropServices.DllImport("codegen/dll/IsarMain/IsarMain.dll", EntryPoint="CSharp_IsarMain_initialize")]
  public static extern void IsarMain_initialize();

  [global::System.Runtime.InteropServices.DllImport("codegen/dll/IsarMain/IsarMain.dll", EntryPoint="CSharp_IsarMain_terminate")]
  public static extern void IsarMain_terminate();
}
