/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 3.0.12
 *
 * This file is not intended to be easily readable and contains a number of
 * coding conventions designed to improve portability and efficiency. Do not make
 * changes to this file unless you know what you are doing--modify the SWIG
 * interface file instead.
 * ----------------------------------------------------------------------------- */


#ifndef SWIGCSHARP
#define SWIGCSHARP
#endif


/* -----------------------------------------------------------------------------
 *  This section contains generic SWIG labels for method/variable
 *  declarations/attributes, and other compiler dependent labels.
 * ----------------------------------------------------------------------------- */

/* template workaround for compilers that cannot correctly implement the C++ standard */
#ifndef SWIGTEMPLATEDISAMBIGUATOR
# if defined(__SUNPRO_CC) && (__SUNPRO_CC <= 0x560)
#  define SWIGTEMPLATEDISAMBIGUATOR template
# elif defined(__HP_aCC)
/* Needed even with `aCC -AA' when `aCC -V' reports HP ANSI C++ B3910B A.03.55 */
/* If we find a maximum version that requires this, the test would be __HP_aCC <= 35500 for A.03.55 */
#  define SWIGTEMPLATEDISAMBIGUATOR template
# else
#  define SWIGTEMPLATEDISAMBIGUATOR
# endif
#endif

/* inline attribute */
#ifndef SWIGINLINE
# if defined(__cplusplus) || (defined(__GNUC__) && !defined(__STRICT_ANSI__))
#   define SWIGINLINE inline
# else
#   define SWIGINLINE
# endif
#endif

/* attribute recognised by some compilers to avoid 'unused' warnings */
#ifndef SWIGUNUSED
# if defined(__GNUC__)
#   if !(defined(__cplusplus)) || (__GNUC__ > 3 || (__GNUC__ == 3 && __GNUC_MINOR__ >= 4))
#     define SWIGUNUSED __attribute__ ((__unused__))
#   else
#     define SWIGUNUSED
#   endif
# elif defined(__ICC)
#   define SWIGUNUSED __attribute__ ((__unused__))
# else
#   define SWIGUNUSED
# endif
#endif

#ifndef SWIG_MSC_UNSUPPRESS_4505
# if defined(_MSC_VER)
#   pragma warning(disable : 4505) /* unreferenced local function has been removed */
# endif
#endif

#ifndef SWIGUNUSEDPARM
# ifdef __cplusplus
#   define SWIGUNUSEDPARM(p)
# else
#   define SWIGUNUSEDPARM(p) p SWIGUNUSED
# endif
#endif

/* internal SWIG method */
#ifndef SWIGINTERN
# define SWIGINTERN static SWIGUNUSED
#endif

/* internal inline SWIG method */
#ifndef SWIGINTERNINLINE
# define SWIGINTERNINLINE SWIGINTERN SWIGINLINE
#endif

/* exporting methods */
#if defined(__GNUC__)
#  if (__GNUC__ >= 4) || (__GNUC__ == 3 && __GNUC_MINOR__ >= 4)
#    ifndef GCC_HASCLASSVISIBILITY
#      define GCC_HASCLASSVISIBILITY
#    endif
#  endif
#endif

#ifndef SWIGEXPORT
# if defined(_WIN32) || defined(__WIN32__) || defined(__CYGWIN__)
#   if defined(STATIC_LINKED)
#     define SWIGEXPORT
#   else
#     define SWIGEXPORT __declspec(dllexport)
#   endif
# else
#   if defined(__GNUC__) && defined(GCC_HASCLASSVISIBILITY)
#     define SWIGEXPORT __attribute__ ((visibility("default")))
#   else
#     define SWIGEXPORT
#   endif
# endif
#endif

/* calling conventions for Windows */
#ifndef SWIGSTDCALL
# if defined(_WIN32) || defined(__WIN32__) || defined(__CYGWIN__)
#   define SWIGSTDCALL __stdcall
# else
#   define SWIGSTDCALL
# endif
#endif

/* Deal with Microsoft's attempt at deprecating C standard runtime functions */
#if !defined(SWIG_NO_CRT_SECURE_NO_DEPRECATE) && defined(_MSC_VER) && !defined(_CRT_SECURE_NO_DEPRECATE)
# define _CRT_SECURE_NO_DEPRECATE
#endif

/* Deal with Microsoft's attempt at deprecating methods in the standard C++ library */
#if !defined(SWIG_NO_SCL_SECURE_NO_DEPRECATE) && defined(_MSC_VER) && !defined(_SCL_SECURE_NO_DEPRECATE)
# define _SCL_SECURE_NO_DEPRECATE
#endif

/* Deal with Apple's deprecated 'AssertMacros.h' from Carbon-framework */
#if defined(__APPLE__) && !defined(__ASSERT_MACROS_DEFINE_VERSIONS_WITHOUT_UNDERSCORES)
# define __ASSERT_MACROS_DEFINE_VERSIONS_WITHOUT_UNDERSCORES 0
#endif

/* Intel's compiler complains if a variable which was never initialised is
 * cast to void, which is a common idiom which we use to indicate that we
 * are aware a variable isn't used.  So we just silence that warning.
 * See: https://github.com/swig/swig/issues/192 for more discussion.
 */
#ifdef __INTEL_COMPILER
# pragma warning disable 592
#endif


#include <stdlib.h>
#include <string.h>
#include <stdio.h>


/* Support for throwing C# exceptions from C/C++. There are two types: 
 * Exceptions that take a message and ArgumentExceptions that take a message and a parameter name. */
typedef enum {
  SWIG_CSharpApplicationException,
  SWIG_CSharpArithmeticException,
  SWIG_CSharpDivideByZeroException,
  SWIG_CSharpIndexOutOfRangeException,
  SWIG_CSharpInvalidCastException,
  SWIG_CSharpInvalidOperationException,
  SWIG_CSharpIOException,
  SWIG_CSharpNullReferenceException,
  SWIG_CSharpOutOfMemoryException,
  SWIG_CSharpOverflowException,
  SWIG_CSharpSystemException
} SWIG_CSharpExceptionCodes;

typedef enum {
  SWIG_CSharpArgumentException,
  SWIG_CSharpArgumentNullException,
  SWIG_CSharpArgumentOutOfRangeException
} SWIG_CSharpExceptionArgumentCodes;

typedef void (SWIGSTDCALL* SWIG_CSharpExceptionCallback_t)(const char *);
typedef void (SWIGSTDCALL* SWIG_CSharpExceptionArgumentCallback_t)(const char *, const char *);

typedef struct {
  SWIG_CSharpExceptionCodes code;
  SWIG_CSharpExceptionCallback_t callback;
} SWIG_CSharpException_t;

typedef struct {
  SWIG_CSharpExceptionArgumentCodes code;
  SWIG_CSharpExceptionArgumentCallback_t callback;
} SWIG_CSharpExceptionArgument_t;

static SWIG_CSharpException_t SWIG_csharp_exceptions[] = {
  { SWIG_CSharpApplicationException, NULL },
  { SWIG_CSharpArithmeticException, NULL },
  { SWIG_CSharpDivideByZeroException, NULL },
  { SWIG_CSharpIndexOutOfRangeException, NULL },
  { SWIG_CSharpInvalidCastException, NULL },
  { SWIG_CSharpInvalidOperationException, NULL },
  { SWIG_CSharpIOException, NULL },
  { SWIG_CSharpNullReferenceException, NULL },
  { SWIG_CSharpOutOfMemoryException, NULL },
  { SWIG_CSharpOverflowException, NULL },
  { SWIG_CSharpSystemException, NULL }
};

static SWIG_CSharpExceptionArgument_t SWIG_csharp_exceptions_argument[] = {
  { SWIG_CSharpArgumentException, NULL },
  { SWIG_CSharpArgumentNullException, NULL },
  { SWIG_CSharpArgumentOutOfRangeException, NULL }
};

static void SWIGUNUSED SWIG_CSharpSetPendingException(SWIG_CSharpExceptionCodes code, const char *msg) {
  SWIG_CSharpExceptionCallback_t callback = SWIG_csharp_exceptions[SWIG_CSharpApplicationException].callback;
  if ((size_t)code < sizeof(SWIG_csharp_exceptions)/sizeof(SWIG_CSharpException_t)) {
    callback = SWIG_csharp_exceptions[code].callback;
  }
  callback(msg);
}

static void SWIGUNUSED SWIG_CSharpSetPendingExceptionArgument(SWIG_CSharpExceptionArgumentCodes code, const char *msg, const char *param_name) {
  SWIG_CSharpExceptionArgumentCallback_t callback = SWIG_csharp_exceptions_argument[SWIG_CSharpArgumentException].callback;
  if ((size_t)code < sizeof(SWIG_csharp_exceptions_argument)/sizeof(SWIG_CSharpExceptionArgument_t)) {
    callback = SWIG_csharp_exceptions_argument[code].callback;
  }
  callback(msg, param_name);
}


#ifdef __cplusplus
extern "C" 
#endif
SWIGEXPORT void SWIGSTDCALL SWIGRegisterExceptionCallbacks_IsarMaincs(
                                                SWIG_CSharpExceptionCallback_t applicationCallback,
                                                SWIG_CSharpExceptionCallback_t arithmeticCallback,
                                                SWIG_CSharpExceptionCallback_t divideByZeroCallback, 
                                                SWIG_CSharpExceptionCallback_t indexOutOfRangeCallback, 
                                                SWIG_CSharpExceptionCallback_t invalidCastCallback,
                                                SWIG_CSharpExceptionCallback_t invalidOperationCallback,
                                                SWIG_CSharpExceptionCallback_t ioCallback,
                                                SWIG_CSharpExceptionCallback_t nullReferenceCallback,
                                                SWIG_CSharpExceptionCallback_t outOfMemoryCallback, 
                                                SWIG_CSharpExceptionCallback_t overflowCallback, 
                                                SWIG_CSharpExceptionCallback_t systemCallback) {
  SWIG_csharp_exceptions[SWIG_CSharpApplicationException].callback = applicationCallback;
  SWIG_csharp_exceptions[SWIG_CSharpArithmeticException].callback = arithmeticCallback;
  SWIG_csharp_exceptions[SWIG_CSharpDivideByZeroException].callback = divideByZeroCallback;
  SWIG_csharp_exceptions[SWIG_CSharpIndexOutOfRangeException].callback = indexOutOfRangeCallback;
  SWIG_csharp_exceptions[SWIG_CSharpInvalidCastException].callback = invalidCastCallback;
  SWIG_csharp_exceptions[SWIG_CSharpInvalidOperationException].callback = invalidOperationCallback;
  SWIG_csharp_exceptions[SWIG_CSharpIOException].callback = ioCallback;
  SWIG_csharp_exceptions[SWIG_CSharpNullReferenceException].callback = nullReferenceCallback;
  SWIG_csharp_exceptions[SWIG_CSharpOutOfMemoryException].callback = outOfMemoryCallback;
  SWIG_csharp_exceptions[SWIG_CSharpOverflowException].callback = overflowCallback;
  SWIG_csharp_exceptions[SWIG_CSharpSystemException].callback = systemCallback;
}

#ifdef __cplusplus
extern "C" 
#endif
SWIGEXPORT void SWIGSTDCALL SWIGRegisterExceptionArgumentCallbacks_IsarMaincs(
                                                SWIG_CSharpExceptionArgumentCallback_t argumentCallback,
                                                SWIG_CSharpExceptionArgumentCallback_t argumentNullCallback,
                                                SWIG_CSharpExceptionArgumentCallback_t argumentOutOfRangeCallback) {
  SWIG_csharp_exceptions_argument[SWIG_CSharpArgumentException].callback = argumentCallback;
  SWIG_csharp_exceptions_argument[SWIG_CSharpArgumentNullException].callback = argumentNullCallback;
  SWIG_csharp_exceptions_argument[SWIG_CSharpArgumentOutOfRangeException].callback = argumentOutOfRangeCallback;
}


/* Callback for returning strings to C# without leaking memory */
typedef char * (SWIGSTDCALL* SWIG_CSharpStringHelperCallback)(const char *);
static SWIG_CSharpStringHelperCallback SWIG_csharp_string_callback = NULL;


#ifdef __cplusplus
extern "C" 
#endif
SWIGEXPORT void SWIGSTDCALL SWIGRegisterStringCallback_IsarMaincs(SWIG_CSharpStringHelperCallback callback) {
  SWIG_csharp_string_callback = callback;
}


/* Contract support */

#define SWIG_contract_assert(nullreturn, expr, msg) if (!(expr)) {SWIG_CSharpSetPendingExceptionArgument(SWIG_CSharpArgumentOutOfRangeException, msg, ""); return nullreturn; } else


typedef double doubleArray;

SWIGINTERN doubleArray *new_doubleArray(int nelements){
  return (double *) calloc(nelements,sizeof(double));
}
SWIGINTERN void delete_doubleArray(doubleArray *self){
  free(self);
}
SWIGINTERN double doubleArray_getitem(doubleArray *self,int index){
  return self[index];
}
SWIGINTERN void doubleArray_setitem(doubleArray *self,int index,double value){
  self[index] = value;
}
SWIGINTERN double *doubleArray_cast(doubleArray *self){
  return self;
}
SWIGINTERN doubleArray *doubleArray_frompointer(double *t){
  return (doubleArray *) t;
}

typedef int intArray;

SWIGINTERN intArray *new_intArray(int nelements){
  return (int *) calloc(nelements,sizeof(int));
}
SWIGINTERN void delete_intArray(intArray *self){
  free(self);
}
SWIGINTERN int intArray_getitem(intArray *self,int index){
  return self[index];
}
SWIGINTERN void intArray_setitem(intArray *self,int index,int value){
  self[index] = value;
}
SWIGINTERN int *intArray_cast(intArray *self){
  return self;
}
SWIGINTERN intArray *intArray_frompointer(int *t){
  return (intArray *) t;
}

#include "codegen/dll/IsarMain/IsarMain_types.h"
#include "codegen/dll/IsarMain/IsarMain.h"
#include "codegen/dll/IsarMain/IsarMain_emxAPI.h"
#include "codegen/dll/IsarMain/IsarMain_initialize.h"
#include "codegen/dll/IsarMain/IsarMain_terminate.h"
// #include "codegen/dll/IsarMain/examples/main.h"

SWIGINTERN void delete_emxArray_real_T(struct emxArray_real_T *self){
        emxDestroyArray_real_T(self);
    }

#ifdef __cplusplus
extern "C" {
#endif

SWIGEXPORT void * SWIGSTDCALL CSharp_new_doubleArray(int jarg1) {
  void * jresult ;
  int arg1 ;
  doubleArray *result = 0 ;
  
  arg1 = (int)jarg1; 
  result = (doubleArray *)new_doubleArray(arg1);
  jresult = (void *)result; 
  return jresult;
}


SWIGEXPORT void SWIGSTDCALL CSharp_delete_doubleArray(void * jarg1) {
  doubleArray *arg1 = (doubleArray *) 0 ;
  
  arg1 = (doubleArray *)jarg1; 
  delete_doubleArray(arg1);
}


SWIGEXPORT double SWIGSTDCALL CSharp_doubleArray_getitem(void * jarg1, int jarg2) {
  double jresult ;
  doubleArray *arg1 = (doubleArray *) 0 ;
  int arg2 ;
  double result;
  
  arg1 = (doubleArray *)jarg1; 
  arg2 = (int)jarg2; 
  result = (double)doubleArray_getitem(arg1,arg2);
  jresult = result; 
  return jresult;
}


SWIGEXPORT void SWIGSTDCALL CSharp_doubleArray_setitem(void * jarg1, int jarg2, double jarg3) {
  doubleArray *arg1 = (doubleArray *) 0 ;
  int arg2 ;
  double arg3 ;
  
  arg1 = (doubleArray *)jarg1; 
  arg2 = (int)jarg2; 
  arg3 = (double)jarg3; 
  doubleArray_setitem(arg1,arg2,arg3);
}


SWIGEXPORT void * SWIGSTDCALL CSharp_doubleArray_cast(void * jarg1) {
  void * jresult ;
  doubleArray *arg1 = (doubleArray *) 0 ;
  double *result = 0 ;
  
  arg1 = (doubleArray *)jarg1; 
  result = (double *)doubleArray_cast(arg1);
  jresult = (void *)result; 
  return jresult;
}


SWIGEXPORT void * SWIGSTDCALL CSharp_doubleArray_frompointer(void * jarg1) {
  void * jresult ;
  double *arg1 = (double *) 0 ;
  doubleArray *result = 0 ;
  
  arg1 = (double *)jarg1; 
  result = (doubleArray *)doubleArray_frompointer(arg1);
  jresult = (void *)result; 
  return jresult;
}


SWIGEXPORT void * SWIGSTDCALL CSharp_new_intArray(int jarg1) {
  void * jresult ;
  int arg1 ;
  intArray *result = 0 ;
  
  arg1 = (int)jarg1; 
  result = (intArray *)new_intArray(arg1);
  jresult = (void *)result; 
  return jresult;
}


SWIGEXPORT void SWIGSTDCALL CSharp_delete_intArray(void * jarg1) {
  intArray *arg1 = (intArray *) 0 ;
  
  arg1 = (intArray *)jarg1; 
  delete_intArray(arg1);
}


SWIGEXPORT int SWIGSTDCALL CSharp_intArray_getitem(void * jarg1, int jarg2) {
  int jresult ;
  intArray *arg1 = (intArray *) 0 ;
  int arg2 ;
  int result;
  
  arg1 = (intArray *)jarg1; 
  arg2 = (int)jarg2; 
  result = (int)intArray_getitem(arg1,arg2);
  jresult = result; 
  return jresult;
}


SWIGEXPORT void SWIGSTDCALL CSharp_intArray_setitem(void * jarg1, int jarg2, int jarg3) {
  intArray *arg1 = (intArray *) 0 ;
  int arg2 ;
  int arg3 ;
  
  arg1 = (intArray *)jarg1; 
  arg2 = (int)jarg2; 
  arg3 = (int)jarg3; 
  intArray_setitem(arg1,arg2,arg3);
}


SWIGEXPORT void * SWIGSTDCALL CSharp_intArray_cast(void * jarg1) {
  void * jresult ;
  intArray *arg1 = (intArray *) 0 ;
  int *result = 0 ;
  
  arg1 = (intArray *)jarg1; 
  result = (int *)intArray_cast(arg1);
  jresult = (void *)result; 
  return jresult;
}


SWIGEXPORT void * SWIGSTDCALL CSharp_intArray_frompointer(void * jarg1) {
  void * jresult ;
  int *arg1 = (int *) 0 ;
  intArray *result = 0 ;
  
  arg1 = (int *)jarg1; 
  result = (intArray *)intArray_frompointer(arg1);
  jresult = (void *)result; 
  return jresult;
}


SWIGEXPORT void SWIGSTDCALL CSharp_emxArray_creal_T_data_set(void * jarg1, void * jarg2) {
  emxArray_creal_T *arg1 = (emxArray_creal_T *) 0 ;
  creal_T *arg2 = (creal_T *) 0 ;
  
  arg1 = (emxArray_creal_T *)jarg1; 
  arg2 = (creal_T *)jarg2; 
  if (arg1) (arg1)->data = arg2;
}


SWIGEXPORT void * SWIGSTDCALL CSharp_emxArray_creal_T_data_get(void * jarg1) {
  void * jresult ;
  emxArray_creal_T *arg1 = (emxArray_creal_T *) 0 ;
  creal_T *result = 0 ;
  
  arg1 = (emxArray_creal_T *)jarg1; 
  result = (creal_T *) ((arg1)->data);
  jresult = (void *)result; 
  return jresult;
}


SWIGEXPORT void SWIGSTDCALL CSharp_emxArray_creal_T_size_set(void * jarg1, void * jarg2) {
  emxArray_creal_T *arg1 = (emxArray_creal_T *) 0 ;
  int32_T *arg2 = (int32_T *) 0 ;
  
  arg1 = (emxArray_creal_T *)jarg1; 
  arg2 = (int32_T *)jarg2; 
  if (arg1) (arg1)->size = arg2;
}


SWIGEXPORT void * SWIGSTDCALL CSharp_emxArray_creal_T_size_get(void * jarg1) {
  void * jresult ;
  emxArray_creal_T *arg1 = (emxArray_creal_T *) 0 ;
  int32_T *result = 0 ;
  
  arg1 = (emxArray_creal_T *)jarg1; 
  result = (int32_T *) ((arg1)->size);
  jresult = (void *)result; 
  return jresult;
}


SWIGEXPORT void SWIGSTDCALL CSharp_emxArray_creal_T_allocatedSize_set(void * jarg1, void * jarg2) {
  emxArray_creal_T *arg1 = (emxArray_creal_T *) 0 ;
  int32_T arg2 ;
  int32_T *argp2 ;
  
  arg1 = (emxArray_creal_T *)jarg1; 
  argp2 = (int32_T *)jarg2; 
  if (!argp2) {
    SWIG_CSharpSetPendingExceptionArgument(SWIG_CSharpArgumentNullException, "Attempt to dereference null int32_T", 0);
    return ;
  }
  arg2 = *argp2; 
  if (arg1) (arg1)->allocatedSize = arg2;
}


SWIGEXPORT void * SWIGSTDCALL CSharp_emxArray_creal_T_allocatedSize_get(void * jarg1) {
  void * jresult ;
  emxArray_creal_T *arg1 = (emxArray_creal_T *) 0 ;
  int32_T result;
  
  arg1 = (emxArray_creal_T *)jarg1; 
  result =  ((arg1)->allocatedSize);
  {
    int32_T * resultptr = (int32_T *) malloc(sizeof(int32_T));
    memmove(resultptr, &result, sizeof(int32_T));
    jresult = resultptr;
  }
  return jresult;
}


SWIGEXPORT void SWIGSTDCALL CSharp_emxArray_creal_T_numDimensions_set(void * jarg1, void * jarg2) {
  emxArray_creal_T *arg1 = (emxArray_creal_T *) 0 ;
  int32_T arg2 ;
  int32_T *argp2 ;
  
  arg1 = (emxArray_creal_T *)jarg1; 
  argp2 = (int32_T *)jarg2; 
  if (!argp2) {
    SWIG_CSharpSetPendingExceptionArgument(SWIG_CSharpArgumentNullException, "Attempt to dereference null int32_T", 0);
    return ;
  }
  arg2 = *argp2; 
  if (arg1) (arg1)->numDimensions = arg2;
}


SWIGEXPORT void * SWIGSTDCALL CSharp_emxArray_creal_T_numDimensions_get(void * jarg1) {
  void * jresult ;
  emxArray_creal_T *arg1 = (emxArray_creal_T *) 0 ;
  int32_T result;
  
  arg1 = (emxArray_creal_T *)jarg1; 
  result =  ((arg1)->numDimensions);
  {
    int32_T * resultptr = (int32_T *) malloc(sizeof(int32_T));
    memmove(resultptr, &result, sizeof(int32_T));
    jresult = resultptr;
  }
  return jresult;
}


SWIGEXPORT void SWIGSTDCALL CSharp_emxArray_creal_T_canFreeData_set(void * jarg1, void * jarg2) {
  emxArray_creal_T *arg1 = (emxArray_creal_T *) 0 ;
  boolean_T arg2 ;
  boolean_T *argp2 ;
  
  arg1 = (emxArray_creal_T *)jarg1; 
  argp2 = (boolean_T *)jarg2; 
  if (!argp2) {
    SWIG_CSharpSetPendingExceptionArgument(SWIG_CSharpArgumentNullException, "Attempt to dereference null boolean_T", 0);
    return ;
  }
  arg2 = *argp2; 
  if (arg1) (arg1)->canFreeData = arg2;
}


SWIGEXPORT void * SWIGSTDCALL CSharp_emxArray_creal_T_canFreeData_get(void * jarg1) {
  void * jresult ;
  emxArray_creal_T *arg1 = (emxArray_creal_T *) 0 ;
  boolean_T result;
  
  arg1 = (emxArray_creal_T *)jarg1; 
  result =  ((arg1)->canFreeData);
  {
    boolean_T * resultptr = (boolean_T *) malloc(sizeof(boolean_T));
    memmove(resultptr, &result, sizeof(boolean_T));
    jresult = resultptr;
  }
  return jresult;
}


SWIGEXPORT void * SWIGSTDCALL CSharp_new_emxArray_creal_T() {
  void * jresult ;
  emxArray_creal_T *result = 0 ;
  
  result = (emxArray_creal_T *)calloc(1, sizeof(emxArray_creal_T));
  jresult = (void *)result; 
  return jresult;
}


SWIGEXPORT void SWIGSTDCALL CSharp_delete_emxArray_creal_T(void * jarg1) {
  emxArray_creal_T *arg1 = (emxArray_creal_T *) 0 ;
  
  arg1 = (emxArray_creal_T *)jarg1; 
  free((char *) arg1);
}


SWIGEXPORT void SWIGSTDCALL CSharp_emxArray_int32_T_data_set(void * jarg1, void * jarg2) {
  struct emxArray_int32_T *arg1 = (struct emxArray_int32_T *) 0 ;
  int32_T *arg2 = (int32_T *) 0 ;
  
  arg1 = (struct emxArray_int32_T *)jarg1; 
  arg2 = (int32_T *)jarg2; 
  if (arg1) (arg1)->data = arg2;
}


SWIGEXPORT void * SWIGSTDCALL CSharp_emxArray_int32_T_data_get(void * jarg1) {
  void * jresult ;
  struct emxArray_int32_T *arg1 = (struct emxArray_int32_T *) 0 ;
  int32_T *result = 0 ;
  
  arg1 = (struct emxArray_int32_T *)jarg1; 
  result = (int32_T *) ((arg1)->data);
  jresult = (void *)result; 
  return jresult;
}


SWIGEXPORT void SWIGSTDCALL CSharp_emxArray_int32_T_size_set(void * jarg1, void * jarg2) {
  struct emxArray_int32_T *arg1 = (struct emxArray_int32_T *) 0 ;
  int32_T *arg2 = (int32_T *) 0 ;
  
  arg1 = (struct emxArray_int32_T *)jarg1; 
  arg2 = (int32_T *)jarg2; 
  if (arg1) (arg1)->size = arg2;
}


SWIGEXPORT void * SWIGSTDCALL CSharp_emxArray_int32_T_size_get(void * jarg1) {
  void * jresult ;
  struct emxArray_int32_T *arg1 = (struct emxArray_int32_T *) 0 ;
  int32_T *result = 0 ;
  
  arg1 = (struct emxArray_int32_T *)jarg1; 
  result = (int32_T *) ((arg1)->size);
  jresult = (void *)result; 
  return jresult;
}


SWIGEXPORT void SWIGSTDCALL CSharp_emxArray_int32_T_allocatedSize_set(void * jarg1, void * jarg2) {
  struct emxArray_int32_T *arg1 = (struct emxArray_int32_T *) 0 ;
  int32_T arg2 ;
  int32_T *argp2 ;
  
  arg1 = (struct emxArray_int32_T *)jarg1; 
  argp2 = (int32_T *)jarg2; 
  if (!argp2) {
    SWIG_CSharpSetPendingExceptionArgument(SWIG_CSharpArgumentNullException, "Attempt to dereference null int32_T", 0);
    return ;
  }
  arg2 = *argp2; 
  if (arg1) (arg1)->allocatedSize = arg2;
}


SWIGEXPORT void * SWIGSTDCALL CSharp_emxArray_int32_T_allocatedSize_get(void * jarg1) {
  void * jresult ;
  struct emxArray_int32_T *arg1 = (struct emxArray_int32_T *) 0 ;
  int32_T result;
  
  arg1 = (struct emxArray_int32_T *)jarg1; 
  result =  ((arg1)->allocatedSize);
  {
    int32_T * resultptr = (int32_T *) malloc(sizeof(int32_T));
    memmove(resultptr, &result, sizeof(int32_T));
    jresult = resultptr;
  }
  return jresult;
}


SWIGEXPORT void SWIGSTDCALL CSharp_emxArray_int32_T_numDimensions_set(void * jarg1, void * jarg2) {
  struct emxArray_int32_T *arg1 = (struct emxArray_int32_T *) 0 ;
  int32_T arg2 ;
  int32_T *argp2 ;
  
  arg1 = (struct emxArray_int32_T *)jarg1; 
  argp2 = (int32_T *)jarg2; 
  if (!argp2) {
    SWIG_CSharpSetPendingExceptionArgument(SWIG_CSharpArgumentNullException, "Attempt to dereference null int32_T", 0);
    return ;
  }
  arg2 = *argp2; 
  if (arg1) (arg1)->numDimensions = arg2;
}


SWIGEXPORT void * SWIGSTDCALL CSharp_emxArray_int32_T_numDimensions_get(void * jarg1) {
  void * jresult ;
  struct emxArray_int32_T *arg1 = (struct emxArray_int32_T *) 0 ;
  int32_T result;
  
  arg1 = (struct emxArray_int32_T *)jarg1; 
  result =  ((arg1)->numDimensions);
  {
    int32_T * resultptr = (int32_T *) malloc(sizeof(int32_T));
    memmove(resultptr, &result, sizeof(int32_T));
    jresult = resultptr;
  }
  return jresult;
}


SWIGEXPORT void SWIGSTDCALL CSharp_emxArray_int32_T_canFreeData_set(void * jarg1, void * jarg2) {
  struct emxArray_int32_T *arg1 = (struct emxArray_int32_T *) 0 ;
  boolean_T arg2 ;
  boolean_T *argp2 ;
  
  arg1 = (struct emxArray_int32_T *)jarg1; 
  argp2 = (boolean_T *)jarg2; 
  if (!argp2) {
    SWIG_CSharpSetPendingExceptionArgument(SWIG_CSharpArgumentNullException, "Attempt to dereference null boolean_T", 0);
    return ;
  }
  arg2 = *argp2; 
  if (arg1) (arg1)->canFreeData = arg2;
}


SWIGEXPORT void * SWIGSTDCALL CSharp_emxArray_int32_T_canFreeData_get(void * jarg1) {
  void * jresult ;
  struct emxArray_int32_T *arg1 = (struct emxArray_int32_T *) 0 ;
  boolean_T result;
  
  arg1 = (struct emxArray_int32_T *)jarg1; 
  result =  ((arg1)->canFreeData);
  {
    boolean_T * resultptr = (boolean_T *) malloc(sizeof(boolean_T));
    memmove(resultptr, &result, sizeof(boolean_T));
    jresult = resultptr;
  }
  return jresult;
}


SWIGEXPORT void * SWIGSTDCALL CSharp_new_emxArray_int32_T() {
  void * jresult ;
  struct emxArray_int32_T *result = 0 ;
  
  result = (struct emxArray_int32_T *)calloc(1, sizeof(struct emxArray_int32_T));
  jresult = (void *)result; 
  return jresult;
}


SWIGEXPORT void SWIGSTDCALL CSharp_delete_emxArray_int32_T(void * jarg1) {
  struct emxArray_int32_T *arg1 = (struct emxArray_int32_T *) 0 ;
  
  arg1 = (struct emxArray_int32_T *)jarg1; 
  free((char *) arg1);
}


SWIGEXPORT void SWIGSTDCALL CSharp_emxArray_int8_T_data_set(void * jarg1, void * jarg2) {
  struct emxArray_int8_T *arg1 = (struct emxArray_int8_T *) 0 ;
  int8_T *arg2 = (int8_T *) 0 ;
  
  arg1 = (struct emxArray_int8_T *)jarg1; 
  arg2 = (int8_T *)jarg2; 
  if (arg1) (arg1)->data = arg2;
}


SWIGEXPORT void * SWIGSTDCALL CSharp_emxArray_int8_T_data_get(void * jarg1) {
  void * jresult ;
  struct emxArray_int8_T *arg1 = (struct emxArray_int8_T *) 0 ;
  int8_T *result = 0 ;
  
  arg1 = (struct emxArray_int8_T *)jarg1; 
  result = (int8_T *) ((arg1)->data);
  jresult = (void *)result; 
  return jresult;
}


SWIGEXPORT void SWIGSTDCALL CSharp_emxArray_int8_T_size_set(void * jarg1, void * jarg2) {
  struct emxArray_int8_T *arg1 = (struct emxArray_int8_T *) 0 ;
  int32_T *arg2 = (int32_T *) 0 ;
  
  arg1 = (struct emxArray_int8_T *)jarg1; 
  arg2 = (int32_T *)jarg2; 
  if (arg1) (arg1)->size = arg2;
}


SWIGEXPORT void * SWIGSTDCALL CSharp_emxArray_int8_T_size_get(void * jarg1) {
  void * jresult ;
  struct emxArray_int8_T *arg1 = (struct emxArray_int8_T *) 0 ;
  int32_T *result = 0 ;
  
  arg1 = (struct emxArray_int8_T *)jarg1; 
  result = (int32_T *) ((arg1)->size);
  jresult = (void *)result; 
  return jresult;
}


SWIGEXPORT void SWIGSTDCALL CSharp_emxArray_int8_T_allocatedSize_set(void * jarg1, void * jarg2) {
  struct emxArray_int8_T *arg1 = (struct emxArray_int8_T *) 0 ;
  int32_T arg2 ;
  int32_T *argp2 ;
  
  arg1 = (struct emxArray_int8_T *)jarg1; 
  argp2 = (int32_T *)jarg2; 
  if (!argp2) {
    SWIG_CSharpSetPendingExceptionArgument(SWIG_CSharpArgumentNullException, "Attempt to dereference null int32_T", 0);
    return ;
  }
  arg2 = *argp2; 
  if (arg1) (arg1)->allocatedSize = arg2;
}


SWIGEXPORT void * SWIGSTDCALL CSharp_emxArray_int8_T_allocatedSize_get(void * jarg1) {
  void * jresult ;
  struct emxArray_int8_T *arg1 = (struct emxArray_int8_T *) 0 ;
  int32_T result;
  
  arg1 = (struct emxArray_int8_T *)jarg1; 
  result =  ((arg1)->allocatedSize);
  {
    int32_T * resultptr = (int32_T *) malloc(sizeof(int32_T));
    memmove(resultptr, &result, sizeof(int32_T));
    jresult = resultptr;
  }
  return jresult;
}


SWIGEXPORT void SWIGSTDCALL CSharp_emxArray_int8_T_numDimensions_set(void * jarg1, void * jarg2) {
  struct emxArray_int8_T *arg1 = (struct emxArray_int8_T *) 0 ;
  int32_T arg2 ;
  int32_T *argp2 ;
  
  arg1 = (struct emxArray_int8_T *)jarg1; 
  argp2 = (int32_T *)jarg2; 
  if (!argp2) {
    SWIG_CSharpSetPendingExceptionArgument(SWIG_CSharpArgumentNullException, "Attempt to dereference null int32_T", 0);
    return ;
  }
  arg2 = *argp2; 
  if (arg1) (arg1)->numDimensions = arg2;
}


SWIGEXPORT void * SWIGSTDCALL CSharp_emxArray_int8_T_numDimensions_get(void * jarg1) {
  void * jresult ;
  struct emxArray_int8_T *arg1 = (struct emxArray_int8_T *) 0 ;
  int32_T result;
  
  arg1 = (struct emxArray_int8_T *)jarg1; 
  result =  ((arg1)->numDimensions);
  {
    int32_T * resultptr = (int32_T *) malloc(sizeof(int32_T));
    memmove(resultptr, &result, sizeof(int32_T));
    jresult = resultptr;
  }
  return jresult;
}


SWIGEXPORT void SWIGSTDCALL CSharp_emxArray_int8_T_canFreeData_set(void * jarg1, void * jarg2) {
  struct emxArray_int8_T *arg1 = (struct emxArray_int8_T *) 0 ;
  boolean_T arg2 ;
  boolean_T *argp2 ;
  
  arg1 = (struct emxArray_int8_T *)jarg1; 
  argp2 = (boolean_T *)jarg2; 
  if (!argp2) {
    SWIG_CSharpSetPendingExceptionArgument(SWIG_CSharpArgumentNullException, "Attempt to dereference null boolean_T", 0);
    return ;
  }
  arg2 = *argp2; 
  if (arg1) (arg1)->canFreeData = arg2;
}


SWIGEXPORT void * SWIGSTDCALL CSharp_emxArray_int8_T_canFreeData_get(void * jarg1) {
  void * jresult ;
  struct emxArray_int8_T *arg1 = (struct emxArray_int8_T *) 0 ;
  boolean_T result;
  
  arg1 = (struct emxArray_int8_T *)jarg1; 
  result =  ((arg1)->canFreeData);
  {
    boolean_T * resultptr = (boolean_T *) malloc(sizeof(boolean_T));
    memmove(resultptr, &result, sizeof(boolean_T));
    jresult = resultptr;
  }
  return jresult;
}


SWIGEXPORT void * SWIGSTDCALL CSharp_new_emxArray_int8_T() {
  void * jresult ;
  struct emxArray_int8_T *result = 0 ;
  
  result = (struct emxArray_int8_T *)calloc(1, sizeof(struct emxArray_int8_T));
  jresult = (void *)result; 
  return jresult;
}


SWIGEXPORT void SWIGSTDCALL CSharp_delete_emxArray_int8_T(void * jarg1) {
  struct emxArray_int8_T *arg1 = (struct emxArray_int8_T *) 0 ;
  
  arg1 = (struct emxArray_int8_T *)jarg1; 
  free((char *) arg1);
}


SWIGEXPORT void SWIGSTDCALL CSharp_emxArray_real_T_data_set(void * jarg1, void * jarg2) {
  struct emxArray_real_T *arg1 = (struct emxArray_real_T *) 0 ;
  real_T *arg2 = (real_T *) 0 ;
  
  arg1 = (struct emxArray_real_T *)jarg1; 
  arg2 = (real_T *)jarg2; 
  if (arg1) (arg1)->data = arg2;
}


SWIGEXPORT void * SWIGSTDCALL CSharp_emxArray_real_T_data_get(void * jarg1) {
  void * jresult ;
  struct emxArray_real_T *arg1 = (struct emxArray_real_T *) 0 ;
  real_T *result = 0 ;
  
  arg1 = (struct emxArray_real_T *)jarg1; 
  result = (real_T *) ((arg1)->data);
  jresult = (void *)result; 
  return jresult;
}


SWIGEXPORT void SWIGSTDCALL CSharp_emxArray_real_T_size_set(void * jarg1, void * jarg2) {
  struct emxArray_real_T *arg1 = (struct emxArray_real_T *) 0 ;
  int32_T *arg2 = (int32_T *) 0 ;
  
  arg1 = (struct emxArray_real_T *)jarg1; 
  arg2 = (int32_T *)jarg2; 
  if (arg1) (arg1)->size = arg2;
}


SWIGEXPORT void * SWIGSTDCALL CSharp_emxArray_real_T_size_get(void * jarg1) {
  void * jresult ;
  struct emxArray_real_T *arg1 = (struct emxArray_real_T *) 0 ;
  int32_T *result = 0 ;
  
  arg1 = (struct emxArray_real_T *)jarg1; 
  result = (int32_T *) ((arg1)->size);
  jresult = (void *)result; 
  return jresult;
}


SWIGEXPORT void SWIGSTDCALL CSharp_emxArray_real_T_allocatedSize_set(void * jarg1, void * jarg2) {
  struct emxArray_real_T *arg1 = (struct emxArray_real_T *) 0 ;
  int32_T arg2 ;
  int32_T *argp2 ;
  
  arg1 = (struct emxArray_real_T *)jarg1; 
  argp2 = (int32_T *)jarg2; 
  if (!argp2) {
    SWIG_CSharpSetPendingExceptionArgument(SWIG_CSharpArgumentNullException, "Attempt to dereference null int32_T", 0);
    return ;
  }
  arg2 = *argp2; 
  if (arg1) (arg1)->allocatedSize = arg2;
}


SWIGEXPORT void * SWIGSTDCALL CSharp_emxArray_real_T_allocatedSize_get(void * jarg1) {
  void * jresult ;
  struct emxArray_real_T *arg1 = (struct emxArray_real_T *) 0 ;
  int32_T result;
  
  arg1 = (struct emxArray_real_T *)jarg1; 
  result =  ((arg1)->allocatedSize);
  {
    int32_T * resultptr = (int32_T *) malloc(sizeof(int32_T));
    memmove(resultptr, &result, sizeof(int32_T));
    jresult = resultptr;
  }
  return jresult;
}


SWIGEXPORT void SWIGSTDCALL CSharp_emxArray_real_T_numDimensions_set(void * jarg1, void * jarg2) {
  struct emxArray_real_T *arg1 = (struct emxArray_real_T *) 0 ;
  int32_T arg2 ;
  int32_T *argp2 ;
  
  arg1 = (struct emxArray_real_T *)jarg1; 
  argp2 = (int32_T *)jarg2; 
  if (!argp2) {
    SWIG_CSharpSetPendingExceptionArgument(SWIG_CSharpArgumentNullException, "Attempt to dereference null int32_T", 0);
    return ;
  }
  arg2 = *argp2; 
  if (arg1) (arg1)->numDimensions = arg2;
}


SWIGEXPORT void * SWIGSTDCALL CSharp_emxArray_real_T_numDimensions_get(void * jarg1) {
  void * jresult ;
  struct emxArray_real_T *arg1 = (struct emxArray_real_T *) 0 ;
  int32_T result;
  
  arg1 = (struct emxArray_real_T *)jarg1; 
  result =  ((arg1)->numDimensions);
  {
    int32_T * resultptr = (int32_T *) malloc(sizeof(int32_T));
    memmove(resultptr, &result, sizeof(int32_T));
    jresult = resultptr;
  }
  return jresult;
}


SWIGEXPORT void SWIGSTDCALL CSharp_emxArray_real_T_canFreeData_set(void * jarg1, void * jarg2) {
  struct emxArray_real_T *arg1 = (struct emxArray_real_T *) 0 ;
  boolean_T arg2 ;
  boolean_T *argp2 ;
  
  arg1 = (struct emxArray_real_T *)jarg1; 
  argp2 = (boolean_T *)jarg2; 
  if (!argp2) {
    SWIG_CSharpSetPendingExceptionArgument(SWIG_CSharpArgumentNullException, "Attempt to dereference null boolean_T", 0);
    return ;
  }
  arg2 = *argp2; 
  if (arg1) (arg1)->canFreeData = arg2;
}


SWIGEXPORT void * SWIGSTDCALL CSharp_emxArray_real_T_canFreeData_get(void * jarg1) {
  void * jresult ;
  struct emxArray_real_T *arg1 = (struct emxArray_real_T *) 0 ;
  boolean_T result;
  
  arg1 = (struct emxArray_real_T *)jarg1; 
  result =  ((arg1)->canFreeData);
  {
    boolean_T * resultptr = (boolean_T *) malloc(sizeof(boolean_T));
    memmove(resultptr, &result, sizeof(boolean_T));
    jresult = resultptr;
  }
  return jresult;
}


SWIGEXPORT void SWIGSTDCALL CSharp_delete_emxArray_real_T(void * jarg1) {
  struct emxArray_real_T *arg1 = (struct emxArray_real_T *) 0 ;
  
  arg1 = (struct emxArray_real_T *)jarg1; 
  delete_emxArray_real_T(arg1);
}


SWIGEXPORT void * SWIGSTDCALL CSharp_new_emxArray_real_T() {
  void * jresult ;
  struct emxArray_real_T *result = 0 ;
  
  result = (struct emxArray_real_T *)calloc(1, sizeof(struct emxArray_real_T));
  jresult = (void *)result; 
  return jresult;
}


SWIGEXPORT void SWIGSTDCALL CSharp_rtBoundsCheckInfo_iFirst_set(void * jarg1, void * jarg2) {
  rtBoundsCheckInfo *arg1 = (rtBoundsCheckInfo *) 0 ;
  int32_T arg2 ;
  int32_T *argp2 ;
  
  arg1 = (rtBoundsCheckInfo *)jarg1; 
  argp2 = (int32_T *)jarg2; 
  if (!argp2) {
    SWIG_CSharpSetPendingExceptionArgument(SWIG_CSharpArgumentNullException, "Attempt to dereference null int32_T", 0);
    return ;
  }
  arg2 = *argp2; 
  if (arg1) (arg1)->iFirst = arg2;
}


SWIGEXPORT void * SWIGSTDCALL CSharp_rtBoundsCheckInfo_iFirst_get(void * jarg1) {
  void * jresult ;
  rtBoundsCheckInfo *arg1 = (rtBoundsCheckInfo *) 0 ;
  int32_T result;
  
  arg1 = (rtBoundsCheckInfo *)jarg1; 
  result =  ((arg1)->iFirst);
  {
    int32_T * resultptr = (int32_T *) malloc(sizeof(int32_T));
    memmove(resultptr, &result, sizeof(int32_T));
    jresult = resultptr;
  }
  return jresult;
}


SWIGEXPORT void SWIGSTDCALL CSharp_rtBoundsCheckInfo_iLast_set(void * jarg1, void * jarg2) {
  rtBoundsCheckInfo *arg1 = (rtBoundsCheckInfo *) 0 ;
  int32_T arg2 ;
  int32_T *argp2 ;
  
  arg1 = (rtBoundsCheckInfo *)jarg1; 
  argp2 = (int32_T *)jarg2; 
  if (!argp2) {
    SWIG_CSharpSetPendingExceptionArgument(SWIG_CSharpArgumentNullException, "Attempt to dereference null int32_T", 0);
    return ;
  }
  arg2 = *argp2; 
  if (arg1) (arg1)->iLast = arg2;
}


SWIGEXPORT void * SWIGSTDCALL CSharp_rtBoundsCheckInfo_iLast_get(void * jarg1) {
  void * jresult ;
  rtBoundsCheckInfo *arg1 = (rtBoundsCheckInfo *) 0 ;
  int32_T result;
  
  arg1 = (rtBoundsCheckInfo *)jarg1; 
  result =  ((arg1)->iLast);
  {
    int32_T * resultptr = (int32_T *) malloc(sizeof(int32_T));
    memmove(resultptr, &result, sizeof(int32_T));
    jresult = resultptr;
  }
  return jresult;
}


SWIGEXPORT void SWIGSTDCALL CSharp_rtBoundsCheckInfo_lineNo_set(void * jarg1, void * jarg2) {
  rtBoundsCheckInfo *arg1 = (rtBoundsCheckInfo *) 0 ;
  int32_T arg2 ;
  int32_T *argp2 ;
  
  arg1 = (rtBoundsCheckInfo *)jarg1; 
  argp2 = (int32_T *)jarg2; 
  if (!argp2) {
    SWIG_CSharpSetPendingExceptionArgument(SWIG_CSharpArgumentNullException, "Attempt to dereference null int32_T", 0);
    return ;
  }
  arg2 = *argp2; 
  if (arg1) (arg1)->lineNo = arg2;
}


SWIGEXPORT void * SWIGSTDCALL CSharp_rtBoundsCheckInfo_lineNo_get(void * jarg1) {
  void * jresult ;
  rtBoundsCheckInfo *arg1 = (rtBoundsCheckInfo *) 0 ;
  int32_T result;
  
  arg1 = (rtBoundsCheckInfo *)jarg1; 
  result =  ((arg1)->lineNo);
  {
    int32_T * resultptr = (int32_T *) malloc(sizeof(int32_T));
    memmove(resultptr, &result, sizeof(int32_T));
    jresult = resultptr;
  }
  return jresult;
}


SWIGEXPORT void SWIGSTDCALL CSharp_rtBoundsCheckInfo_colNo_set(void * jarg1, void * jarg2) {
  rtBoundsCheckInfo *arg1 = (rtBoundsCheckInfo *) 0 ;
  int32_T arg2 ;
  int32_T *argp2 ;
  
  arg1 = (rtBoundsCheckInfo *)jarg1; 
  argp2 = (int32_T *)jarg2; 
  if (!argp2) {
    SWIG_CSharpSetPendingExceptionArgument(SWIG_CSharpArgumentNullException, "Attempt to dereference null int32_T", 0);
    return ;
  }
  arg2 = *argp2; 
  if (arg1) (arg1)->colNo = arg2;
}


SWIGEXPORT void * SWIGSTDCALL CSharp_rtBoundsCheckInfo_colNo_get(void * jarg1) {
  void * jresult ;
  rtBoundsCheckInfo *arg1 = (rtBoundsCheckInfo *) 0 ;
  int32_T result;
  
  arg1 = (rtBoundsCheckInfo *)jarg1; 
  result =  ((arg1)->colNo);
  {
    int32_T * resultptr = (int32_T *) malloc(sizeof(int32_T));
    memmove(resultptr, &result, sizeof(int32_T));
    jresult = resultptr;
  }
  return jresult;
}


SWIGEXPORT void SWIGSTDCALL CSharp_rtBoundsCheckInfo_aName_set(void * jarg1, char * jarg2) {
  rtBoundsCheckInfo *arg1 = (rtBoundsCheckInfo *) 0 ;
  char *arg2 = (char *) 0 ;
  
  arg1 = (rtBoundsCheckInfo *)jarg1; 
  arg2 = (char *)jarg2; 
  {
    if (arg2) {
      arg1->aName = (char const *) malloc(strlen((const char *)arg2)+1);
      strcpy((char *)arg1->aName, (const char *)arg2);
    } else {
      arg1->aName = 0;
    }
  }
}


SWIGEXPORT char * SWIGSTDCALL CSharp_rtBoundsCheckInfo_aName_get(void * jarg1) {
  char * jresult ;
  rtBoundsCheckInfo *arg1 = (rtBoundsCheckInfo *) 0 ;
  char *result = 0 ;
  
  arg1 = (rtBoundsCheckInfo *)jarg1; 
  result = (char *) ((arg1)->aName);
  jresult = SWIG_csharp_string_callback((const char *)result); 
  return jresult;
}


SWIGEXPORT void SWIGSTDCALL CSharp_rtBoundsCheckInfo_fName_set(void * jarg1, char * jarg2) {
  rtBoundsCheckInfo *arg1 = (rtBoundsCheckInfo *) 0 ;
  char *arg2 = (char *) 0 ;
  
  arg1 = (rtBoundsCheckInfo *)jarg1; 
  arg2 = (char *)jarg2; 
  {
    if (arg2) {
      arg1->fName = (char const *) malloc(strlen((const char *)arg2)+1);
      strcpy((char *)arg1->fName, (const char *)arg2);
    } else {
      arg1->fName = 0;
    }
  }
}


SWIGEXPORT char * SWIGSTDCALL CSharp_rtBoundsCheckInfo_fName_get(void * jarg1) {
  char * jresult ;
  rtBoundsCheckInfo *arg1 = (rtBoundsCheckInfo *) 0 ;
  char *result = 0 ;
  
  arg1 = (rtBoundsCheckInfo *)jarg1; 
  result = (char *) ((arg1)->fName);
  jresult = SWIG_csharp_string_callback((const char *)result); 
  return jresult;
}


SWIGEXPORT void SWIGSTDCALL CSharp_rtBoundsCheckInfo_pName_set(void * jarg1, char * jarg2) {
  rtBoundsCheckInfo *arg1 = (rtBoundsCheckInfo *) 0 ;
  char *arg2 = (char *) 0 ;
  
  arg1 = (rtBoundsCheckInfo *)jarg1; 
  arg2 = (char *)jarg2; 
  {
    if (arg2) {
      arg1->pName = (char const *) malloc(strlen((const char *)arg2)+1);
      strcpy((char *)arg1->pName, (const char *)arg2);
    } else {
      arg1->pName = 0;
    }
  }
}


SWIGEXPORT char * SWIGSTDCALL CSharp_rtBoundsCheckInfo_pName_get(void * jarg1) {
  char * jresult ;
  rtBoundsCheckInfo *arg1 = (rtBoundsCheckInfo *) 0 ;
  char *result = 0 ;
  
  arg1 = (rtBoundsCheckInfo *)jarg1; 
  result = (char *) ((arg1)->pName);
  jresult = SWIG_csharp_string_callback((const char *)result); 
  return jresult;
}


SWIGEXPORT void SWIGSTDCALL CSharp_rtBoundsCheckInfo_checkKind_set(void * jarg1, void * jarg2) {
  rtBoundsCheckInfo *arg1 = (rtBoundsCheckInfo *) 0 ;
  int32_T arg2 ;
  int32_T *argp2 ;
  
  arg1 = (rtBoundsCheckInfo *)jarg1; 
  argp2 = (int32_T *)jarg2; 
  if (!argp2) {
    SWIG_CSharpSetPendingExceptionArgument(SWIG_CSharpArgumentNullException, "Attempt to dereference null int32_T", 0);
    return ;
  }
  arg2 = *argp2; 
  if (arg1) (arg1)->checkKind = arg2;
}


SWIGEXPORT void * SWIGSTDCALL CSharp_rtBoundsCheckInfo_checkKind_get(void * jarg1) {
  void * jresult ;
  rtBoundsCheckInfo *arg1 = (rtBoundsCheckInfo *) 0 ;
  int32_T result;
  
  arg1 = (rtBoundsCheckInfo *)jarg1; 
  result =  ((arg1)->checkKind);
  {
    int32_T * resultptr = (int32_T *) malloc(sizeof(int32_T));
    memmove(resultptr, &result, sizeof(int32_T));
    jresult = resultptr;
  }
  return jresult;
}


SWIGEXPORT void * SWIGSTDCALL CSharp_new_rtBoundsCheckInfo() {
  void * jresult ;
  rtBoundsCheckInfo *result = 0 ;
  
  result = (rtBoundsCheckInfo *)calloc(1, sizeof(rtBoundsCheckInfo));
  jresult = (void *)result; 
  return jresult;
}


SWIGEXPORT void SWIGSTDCALL CSharp_delete_rtBoundsCheckInfo(void * jarg1) {
  rtBoundsCheckInfo *arg1 = (rtBoundsCheckInfo *) 0 ;
  
  arg1 = (rtBoundsCheckInfo *)jarg1; 
  free((char *) arg1);
}


SWIGEXPORT void SWIGSTDCALL CSharp_rtDoubleCheckInfo_lineNo_set(void * jarg1, void * jarg2) {
  rtDoubleCheckInfo *arg1 = (rtDoubleCheckInfo *) 0 ;
  int32_T arg2 ;
  int32_T *argp2 ;
  
  arg1 = (rtDoubleCheckInfo *)jarg1; 
  argp2 = (int32_T *)jarg2; 
  if (!argp2) {
    SWIG_CSharpSetPendingExceptionArgument(SWIG_CSharpArgumentNullException, "Attempt to dereference null int32_T", 0);
    return ;
  }
  arg2 = *argp2; 
  if (arg1) (arg1)->lineNo = arg2;
}


SWIGEXPORT void * SWIGSTDCALL CSharp_rtDoubleCheckInfo_lineNo_get(void * jarg1) {
  void * jresult ;
  rtDoubleCheckInfo *arg1 = (rtDoubleCheckInfo *) 0 ;
  int32_T result;
  
  arg1 = (rtDoubleCheckInfo *)jarg1; 
  result =  ((arg1)->lineNo);
  {
    int32_T * resultptr = (int32_T *) malloc(sizeof(int32_T));
    memmove(resultptr, &result, sizeof(int32_T));
    jresult = resultptr;
  }
  return jresult;
}


SWIGEXPORT void SWIGSTDCALL CSharp_rtDoubleCheckInfo_colNo_set(void * jarg1, void * jarg2) {
  rtDoubleCheckInfo *arg1 = (rtDoubleCheckInfo *) 0 ;
  int32_T arg2 ;
  int32_T *argp2 ;
  
  arg1 = (rtDoubleCheckInfo *)jarg1; 
  argp2 = (int32_T *)jarg2; 
  if (!argp2) {
    SWIG_CSharpSetPendingExceptionArgument(SWIG_CSharpArgumentNullException, "Attempt to dereference null int32_T", 0);
    return ;
  }
  arg2 = *argp2; 
  if (arg1) (arg1)->colNo = arg2;
}


SWIGEXPORT void * SWIGSTDCALL CSharp_rtDoubleCheckInfo_colNo_get(void * jarg1) {
  void * jresult ;
  rtDoubleCheckInfo *arg1 = (rtDoubleCheckInfo *) 0 ;
  int32_T result;
  
  arg1 = (rtDoubleCheckInfo *)jarg1; 
  result =  ((arg1)->colNo);
  {
    int32_T * resultptr = (int32_T *) malloc(sizeof(int32_T));
    memmove(resultptr, &result, sizeof(int32_T));
    jresult = resultptr;
  }
  return jresult;
}


SWIGEXPORT void SWIGSTDCALL CSharp_rtDoubleCheckInfo_fName_set(void * jarg1, char * jarg2) {
  rtDoubleCheckInfo *arg1 = (rtDoubleCheckInfo *) 0 ;
  char *arg2 = (char *) 0 ;
  
  arg1 = (rtDoubleCheckInfo *)jarg1; 
  arg2 = (char *)jarg2; 
  {
    if (arg2) {
      arg1->fName = (char const *) malloc(strlen((const char *)arg2)+1);
      strcpy((char *)arg1->fName, (const char *)arg2);
    } else {
      arg1->fName = 0;
    }
  }
}


SWIGEXPORT char * SWIGSTDCALL CSharp_rtDoubleCheckInfo_fName_get(void * jarg1) {
  char * jresult ;
  rtDoubleCheckInfo *arg1 = (rtDoubleCheckInfo *) 0 ;
  char *result = 0 ;
  
  arg1 = (rtDoubleCheckInfo *)jarg1; 
  result = (char *) ((arg1)->fName);
  jresult = SWIG_csharp_string_callback((const char *)result); 
  return jresult;
}


SWIGEXPORT void SWIGSTDCALL CSharp_rtDoubleCheckInfo_pName_set(void * jarg1, char * jarg2) {
  rtDoubleCheckInfo *arg1 = (rtDoubleCheckInfo *) 0 ;
  char *arg2 = (char *) 0 ;
  
  arg1 = (rtDoubleCheckInfo *)jarg1; 
  arg2 = (char *)jarg2; 
  {
    if (arg2) {
      arg1->pName = (char const *) malloc(strlen((const char *)arg2)+1);
      strcpy((char *)arg1->pName, (const char *)arg2);
    } else {
      arg1->pName = 0;
    }
  }
}


SWIGEXPORT char * SWIGSTDCALL CSharp_rtDoubleCheckInfo_pName_get(void * jarg1) {
  char * jresult ;
  rtDoubleCheckInfo *arg1 = (rtDoubleCheckInfo *) 0 ;
  char *result = 0 ;
  
  arg1 = (rtDoubleCheckInfo *)jarg1; 
  result = (char *) ((arg1)->pName);
  jresult = SWIG_csharp_string_callback((const char *)result); 
  return jresult;
}


SWIGEXPORT void SWIGSTDCALL CSharp_rtDoubleCheckInfo_checkKind_set(void * jarg1, void * jarg2) {
  rtDoubleCheckInfo *arg1 = (rtDoubleCheckInfo *) 0 ;
  int32_T arg2 ;
  int32_T *argp2 ;
  
  arg1 = (rtDoubleCheckInfo *)jarg1; 
  argp2 = (int32_T *)jarg2; 
  if (!argp2) {
    SWIG_CSharpSetPendingExceptionArgument(SWIG_CSharpArgumentNullException, "Attempt to dereference null int32_T", 0);
    return ;
  }
  arg2 = *argp2; 
  if (arg1) (arg1)->checkKind = arg2;
}


SWIGEXPORT void * SWIGSTDCALL CSharp_rtDoubleCheckInfo_checkKind_get(void * jarg1) {
  void * jresult ;
  rtDoubleCheckInfo *arg1 = (rtDoubleCheckInfo *) 0 ;
  int32_T result;
  
  arg1 = (rtDoubleCheckInfo *)jarg1; 
  result =  ((arg1)->checkKind);
  {
    int32_T * resultptr = (int32_T *) malloc(sizeof(int32_T));
    memmove(resultptr, &result, sizeof(int32_T));
    jresult = resultptr;
  }
  return jresult;
}


SWIGEXPORT void * SWIGSTDCALL CSharp_new_rtDoubleCheckInfo() {
  void * jresult ;
  rtDoubleCheckInfo *result = 0 ;
  
  result = (rtDoubleCheckInfo *)calloc(1, sizeof(rtDoubleCheckInfo));
  jresult = (void *)result; 
  return jresult;
}


SWIGEXPORT void SWIGSTDCALL CSharp_delete_rtDoubleCheckInfo(void * jarg1) {
  rtDoubleCheckInfo *arg1 = (rtDoubleCheckInfo *) 0 ;
  
  arg1 = (rtDoubleCheckInfo *)jarg1; 
  free((char *) arg1);
}


SWIGEXPORT void SWIGSTDCALL CSharp_rtEqualityCheckInfo_nDims_set(void * jarg1, void * jarg2) {
  rtEqualityCheckInfo *arg1 = (rtEqualityCheckInfo *) 0 ;
  int32_T arg2 ;
  int32_T *argp2 ;
  
  arg1 = (rtEqualityCheckInfo *)jarg1; 
  argp2 = (int32_T *)jarg2; 
  if (!argp2) {
    SWIG_CSharpSetPendingExceptionArgument(SWIG_CSharpArgumentNullException, "Attempt to dereference null int32_T", 0);
    return ;
  }
  arg2 = *argp2; 
  if (arg1) (arg1)->nDims = arg2;
}


SWIGEXPORT void * SWIGSTDCALL CSharp_rtEqualityCheckInfo_nDims_get(void * jarg1) {
  void * jresult ;
  rtEqualityCheckInfo *arg1 = (rtEqualityCheckInfo *) 0 ;
  int32_T result;
  
  arg1 = (rtEqualityCheckInfo *)jarg1; 
  result =  ((arg1)->nDims);
  {
    int32_T * resultptr = (int32_T *) malloc(sizeof(int32_T));
    memmove(resultptr, &result, sizeof(int32_T));
    jresult = resultptr;
  }
  return jresult;
}


SWIGEXPORT void SWIGSTDCALL CSharp_rtEqualityCheckInfo_lineNo_set(void * jarg1, void * jarg2) {
  rtEqualityCheckInfo *arg1 = (rtEqualityCheckInfo *) 0 ;
  int32_T arg2 ;
  int32_T *argp2 ;
  
  arg1 = (rtEqualityCheckInfo *)jarg1; 
  argp2 = (int32_T *)jarg2; 
  if (!argp2) {
    SWIG_CSharpSetPendingExceptionArgument(SWIG_CSharpArgumentNullException, "Attempt to dereference null int32_T", 0);
    return ;
  }
  arg2 = *argp2; 
  if (arg1) (arg1)->lineNo = arg2;
}


SWIGEXPORT void * SWIGSTDCALL CSharp_rtEqualityCheckInfo_lineNo_get(void * jarg1) {
  void * jresult ;
  rtEqualityCheckInfo *arg1 = (rtEqualityCheckInfo *) 0 ;
  int32_T result;
  
  arg1 = (rtEqualityCheckInfo *)jarg1; 
  result =  ((arg1)->lineNo);
  {
    int32_T * resultptr = (int32_T *) malloc(sizeof(int32_T));
    memmove(resultptr, &result, sizeof(int32_T));
    jresult = resultptr;
  }
  return jresult;
}


SWIGEXPORT void SWIGSTDCALL CSharp_rtEqualityCheckInfo_colNo_set(void * jarg1, void * jarg2) {
  rtEqualityCheckInfo *arg1 = (rtEqualityCheckInfo *) 0 ;
  int32_T arg2 ;
  int32_T *argp2 ;
  
  arg1 = (rtEqualityCheckInfo *)jarg1; 
  argp2 = (int32_T *)jarg2; 
  if (!argp2) {
    SWIG_CSharpSetPendingExceptionArgument(SWIG_CSharpArgumentNullException, "Attempt to dereference null int32_T", 0);
    return ;
  }
  arg2 = *argp2; 
  if (arg1) (arg1)->colNo = arg2;
}


SWIGEXPORT void * SWIGSTDCALL CSharp_rtEqualityCheckInfo_colNo_get(void * jarg1) {
  void * jresult ;
  rtEqualityCheckInfo *arg1 = (rtEqualityCheckInfo *) 0 ;
  int32_T result;
  
  arg1 = (rtEqualityCheckInfo *)jarg1; 
  result =  ((arg1)->colNo);
  {
    int32_T * resultptr = (int32_T *) malloc(sizeof(int32_T));
    memmove(resultptr, &result, sizeof(int32_T));
    jresult = resultptr;
  }
  return jresult;
}


SWIGEXPORT void SWIGSTDCALL CSharp_rtEqualityCheckInfo_fName_set(void * jarg1, char * jarg2) {
  rtEqualityCheckInfo *arg1 = (rtEqualityCheckInfo *) 0 ;
  char *arg2 = (char *) 0 ;
  
  arg1 = (rtEqualityCheckInfo *)jarg1; 
  arg2 = (char *)jarg2; 
  {
    if (arg2) {
      arg1->fName = (char const *) malloc(strlen((const char *)arg2)+1);
      strcpy((char *)arg1->fName, (const char *)arg2);
    } else {
      arg1->fName = 0;
    }
  }
}


SWIGEXPORT char * SWIGSTDCALL CSharp_rtEqualityCheckInfo_fName_get(void * jarg1) {
  char * jresult ;
  rtEqualityCheckInfo *arg1 = (rtEqualityCheckInfo *) 0 ;
  char *result = 0 ;
  
  arg1 = (rtEqualityCheckInfo *)jarg1; 
  result = (char *) ((arg1)->fName);
  jresult = SWIG_csharp_string_callback((const char *)result); 
  return jresult;
}


SWIGEXPORT void SWIGSTDCALL CSharp_rtEqualityCheckInfo_pName_set(void * jarg1, char * jarg2) {
  rtEqualityCheckInfo *arg1 = (rtEqualityCheckInfo *) 0 ;
  char *arg2 = (char *) 0 ;
  
  arg1 = (rtEqualityCheckInfo *)jarg1; 
  arg2 = (char *)jarg2; 
  {
    if (arg2) {
      arg1->pName = (char const *) malloc(strlen((const char *)arg2)+1);
      strcpy((char *)arg1->pName, (const char *)arg2);
    } else {
      arg1->pName = 0;
    }
  }
}


SWIGEXPORT char * SWIGSTDCALL CSharp_rtEqualityCheckInfo_pName_get(void * jarg1) {
  char * jresult ;
  rtEqualityCheckInfo *arg1 = (rtEqualityCheckInfo *) 0 ;
  char *result = 0 ;
  
  arg1 = (rtEqualityCheckInfo *)jarg1; 
  result = (char *) ((arg1)->pName);
  jresult = SWIG_csharp_string_callback((const char *)result); 
  return jresult;
}


SWIGEXPORT void * SWIGSTDCALL CSharp_new_rtEqualityCheckInfo() {
  void * jresult ;
  rtEqualityCheckInfo *result = 0 ;
  
  result = (rtEqualityCheckInfo *)calloc(1, sizeof(rtEqualityCheckInfo));
  jresult = (void *)result; 
  return jresult;
}


SWIGEXPORT void SWIGSTDCALL CSharp_delete_rtEqualityCheckInfo(void * jarg1) {
  rtEqualityCheckInfo *arg1 = (rtEqualityCheckInfo *) 0 ;
  
  arg1 = (rtEqualityCheckInfo *)jarg1; 
  free((char *) arg1);
}


SWIGEXPORT void SWIGSTDCALL CSharp_rtRunTimeErrorInfo_lineNo_set(void * jarg1, void * jarg2) {
  rtRunTimeErrorInfo *arg1 = (rtRunTimeErrorInfo *) 0 ;
  int32_T arg2 ;
  int32_T *argp2 ;
  
  arg1 = (rtRunTimeErrorInfo *)jarg1; 
  argp2 = (int32_T *)jarg2; 
  if (!argp2) {
    SWIG_CSharpSetPendingExceptionArgument(SWIG_CSharpArgumentNullException, "Attempt to dereference null int32_T", 0);
    return ;
  }
  arg2 = *argp2; 
  if (arg1) (arg1)->lineNo = arg2;
}


SWIGEXPORT void * SWIGSTDCALL CSharp_rtRunTimeErrorInfo_lineNo_get(void * jarg1) {
  void * jresult ;
  rtRunTimeErrorInfo *arg1 = (rtRunTimeErrorInfo *) 0 ;
  int32_T result;
  
  arg1 = (rtRunTimeErrorInfo *)jarg1; 
  result =  ((arg1)->lineNo);
  {
    int32_T * resultptr = (int32_T *) malloc(sizeof(int32_T));
    memmove(resultptr, &result, sizeof(int32_T));
    jresult = resultptr;
  }
  return jresult;
}


SWIGEXPORT void SWIGSTDCALL CSharp_rtRunTimeErrorInfo_colNo_set(void * jarg1, void * jarg2) {
  rtRunTimeErrorInfo *arg1 = (rtRunTimeErrorInfo *) 0 ;
  int32_T arg2 ;
  int32_T *argp2 ;
  
  arg1 = (rtRunTimeErrorInfo *)jarg1; 
  argp2 = (int32_T *)jarg2; 
  if (!argp2) {
    SWIG_CSharpSetPendingExceptionArgument(SWIG_CSharpArgumentNullException, "Attempt to dereference null int32_T", 0);
    return ;
  }
  arg2 = *argp2; 
  if (arg1) (arg1)->colNo = arg2;
}


SWIGEXPORT void * SWIGSTDCALL CSharp_rtRunTimeErrorInfo_colNo_get(void * jarg1) {
  void * jresult ;
  rtRunTimeErrorInfo *arg1 = (rtRunTimeErrorInfo *) 0 ;
  int32_T result;
  
  arg1 = (rtRunTimeErrorInfo *)jarg1; 
  result =  ((arg1)->colNo);
  {
    int32_T * resultptr = (int32_T *) malloc(sizeof(int32_T));
    memmove(resultptr, &result, sizeof(int32_T));
    jresult = resultptr;
  }
  return jresult;
}


SWIGEXPORT void SWIGSTDCALL CSharp_rtRunTimeErrorInfo_fName_set(void * jarg1, char * jarg2) {
  rtRunTimeErrorInfo *arg1 = (rtRunTimeErrorInfo *) 0 ;
  char *arg2 = (char *) 0 ;
  
  arg1 = (rtRunTimeErrorInfo *)jarg1; 
  arg2 = (char *)jarg2; 
  {
    if (arg2) {
      arg1->fName = (char const *) malloc(strlen((const char *)arg2)+1);
      strcpy((char *)arg1->fName, (const char *)arg2);
    } else {
      arg1->fName = 0;
    }
  }
}


SWIGEXPORT char * SWIGSTDCALL CSharp_rtRunTimeErrorInfo_fName_get(void * jarg1) {
  char * jresult ;
  rtRunTimeErrorInfo *arg1 = (rtRunTimeErrorInfo *) 0 ;
  char *result = 0 ;
  
  arg1 = (rtRunTimeErrorInfo *)jarg1; 
  result = (char *) ((arg1)->fName);
  jresult = SWIG_csharp_string_callback((const char *)result); 
  return jresult;
}


SWIGEXPORT void SWIGSTDCALL CSharp_rtRunTimeErrorInfo_pName_set(void * jarg1, char * jarg2) {
  rtRunTimeErrorInfo *arg1 = (rtRunTimeErrorInfo *) 0 ;
  char *arg2 = (char *) 0 ;
  
  arg1 = (rtRunTimeErrorInfo *)jarg1; 
  arg2 = (char *)jarg2; 
  {
    if (arg2) {
      arg1->pName = (char const *) malloc(strlen((const char *)arg2)+1);
      strcpy((char *)arg1->pName, (const char *)arg2);
    } else {
      arg1->pName = 0;
    }
  }
}


SWIGEXPORT char * SWIGSTDCALL CSharp_rtRunTimeErrorInfo_pName_get(void * jarg1) {
  char * jresult ;
  rtRunTimeErrorInfo *arg1 = (rtRunTimeErrorInfo *) 0 ;
  char *result = 0 ;
  
  arg1 = (rtRunTimeErrorInfo *)jarg1; 
  result = (char *) ((arg1)->pName);
  jresult = SWIG_csharp_string_callback((const char *)result); 
  return jresult;
}


SWIGEXPORT void * SWIGSTDCALL CSharp_new_rtRunTimeErrorInfo() {
  void * jresult ;
  rtRunTimeErrorInfo *result = 0 ;
  
  result = (rtRunTimeErrorInfo *)calloc(1, sizeof(rtRunTimeErrorInfo));
  jresult = (void *)result; 
  return jresult;
}


SWIGEXPORT void SWIGSTDCALL CSharp_delete_rtRunTimeErrorInfo(void * jarg1) {
  rtRunTimeErrorInfo *arg1 = (rtRunTimeErrorInfo *) 0 ;
  
  arg1 = (rtRunTimeErrorInfo *)jarg1; 
  free((char *) arg1);
}


SWIGEXPORT void SWIGSTDCALL CSharp_IsarMain(void * jarg1, void * jarg2, void * jarg3, void * jarg4, void * jarg5, void * jarg6, void * jarg7, void * jarg8, void * jarg9) {
  emxArray_real_T *arg1 = (emxArray_real_T *) 0 ;
  emxArray_real_T *arg2 = (emxArray_real_T *) 0 ;
  emxArray_real_T *arg3 = (emxArray_real_T *) 0 ;
  real_T *arg4 = (real_T *) 0 ;
  real_T *arg5 = (real_T *) 0 ;
  emxArray_real_T *arg6 = (emxArray_real_T *) 0 ;
  emxArray_real_T *arg7 = (emxArray_real_T *) 0 ;
  emxArray_real_T *arg8 = (emxArray_real_T *) 0 ;
  emxArray_real_T *arg9 = (emxArray_real_T *) 0 ;
  
  arg1 = (emxArray_real_T *)jarg1; 
  arg2 = (emxArray_real_T *)jarg2; 
  arg3 = (emxArray_real_T *)jarg3; 
  arg4 = (real_T *)jarg4; 
  arg5 = (real_T *)jarg5; 
  arg6 = (emxArray_real_T *)jarg6; 
  arg7 = (emxArray_real_T *)jarg7; 
  arg8 = (emxArray_real_T *)jarg8; 
  arg9 = (emxArray_real_T *)jarg9; 
  IsarMain((struct emxArray_real_T const *)arg1,arg2,arg3,arg4,arg5,arg6,arg7,arg8,arg9);
}


SWIGEXPORT void * SWIGSTDCALL CSharp_emxCreateND_real_T(void * jarg1, void * jarg2) {
  void * jresult ;
  int32_T arg1 ;
  int32_T *arg2 = (int32_T *) 0 ;
  int32_T *argp1 ;
  emxArray_real_T *result = 0 ;
  
  argp1 = (int32_T *)jarg1; 
  if (!argp1) {
    SWIG_CSharpSetPendingExceptionArgument(SWIG_CSharpArgumentNullException, "Attempt to dereference null int32_T", 0);
    return 0;
  }
  arg1 = *argp1; 
  arg2 = (int32_T *)jarg2; 
  result = (emxArray_real_T *)emxCreateND_real_T(arg1,arg2);
  jresult = (void *)result; 
  return jresult;
}


SWIGEXPORT void * SWIGSTDCALL CSharp_emxCreateWrapperND_real_T(void * jarg1, void * jarg2, void * jarg3) {
  void * jresult ;
  real_T *arg1 = (real_T *) 0 ;
  int32_T arg2 ;
  int32_T *arg3 = (int32_T *) 0 ;
  int32_T *argp2 ;
  emxArray_real_T *result = 0 ;
  
  arg1 = (real_T *)jarg1; 
  argp2 = (int32_T *)jarg2; 
  if (!argp2) {
    SWIG_CSharpSetPendingExceptionArgument(SWIG_CSharpArgumentNullException, "Attempt to dereference null int32_T", 0);
    return 0;
  }
  arg2 = *argp2; 
  arg3 = (int32_T *)jarg3; 
  result = (emxArray_real_T *)emxCreateWrapperND_real_T(arg1,arg2,arg3);
  jresult = (void *)result; 
  return jresult;
}


SWIGEXPORT void * SWIGSTDCALL CSharp_emxCreateWrapper_real_T(void * jarg1, void * jarg2, void * jarg3) {
  void * jresult ;
  real_T *arg1 = (real_T *) 0 ;
  int32_T arg2 ;
  int32_T arg3 ;
  int32_T *argp2 ;
  int32_T *argp3 ;
  emxArray_real_T *result = 0 ;
  
  arg1 = (real_T *)jarg1; 
  argp2 = (int32_T *)jarg2; 
  if (!argp2) {
    SWIG_CSharpSetPendingExceptionArgument(SWIG_CSharpArgumentNullException, "Attempt to dereference null int32_T", 0);
    return 0;
  }
  arg2 = *argp2; 
  argp3 = (int32_T *)jarg3; 
  if (!argp3) {
    SWIG_CSharpSetPendingExceptionArgument(SWIG_CSharpArgumentNullException, "Attempt to dereference null int32_T", 0);
    return 0;
  }
  arg3 = *argp3; 
  result = (emxArray_real_T *)emxCreateWrapper_real_T(arg1,arg2,arg3);
  jresult = (void *)result; 
  return jresult;
}


SWIGEXPORT void * SWIGSTDCALL CSharp_emxCreate_real_T(void * jarg1, void * jarg2) {
  void * jresult ;
  int32_T arg1 ;
  int32_T arg2 ;
  int32_T *argp1 ;
  int32_T *argp2 ;
  emxArray_real_T *result = 0 ;
  
  argp1 = (int32_T *)jarg1; 
  if (!argp1) {
    SWIG_CSharpSetPendingExceptionArgument(SWIG_CSharpArgumentNullException, "Attempt to dereference null int32_T", 0);
    return 0;
  }
  arg1 = *argp1; 
  argp2 = (int32_T *)jarg2; 
  if (!argp2) {
    SWIG_CSharpSetPendingExceptionArgument(SWIG_CSharpArgumentNullException, "Attempt to dereference null int32_T", 0);
    return 0;
  }
  arg2 = *argp2; 
  result = (emxArray_real_T *)emxCreate_real_T(arg1,arg2);
  jresult = (void *)result; 
  return jresult;
}


SWIGEXPORT void SWIGSTDCALL CSharp_emxDestroyArray_real_T(void * jarg1) {
  emxArray_real_T *arg1 = (emxArray_real_T *) 0 ;
  
  arg1 = (emxArray_real_T *)jarg1; 
  emxDestroyArray_real_T(arg1);
}


SWIGEXPORT void SWIGSTDCALL CSharp_emxInitArray_real_T(void * jarg1, void * jarg2) {
  emxArray_real_T **arg1 = (emxArray_real_T **) 0 ;
  int32_T arg2 ;
  int32_T *argp2 ;
  
  arg1 = (emxArray_real_T **)jarg1; 
  argp2 = (int32_T *)jarg2; 
  if (!argp2) {
    SWIG_CSharpSetPendingExceptionArgument(SWIG_CSharpArgumentNullException, "Attempt to dereference null int32_T", 0);
    return ;
  }
  arg2 = *argp2; 
  emxInitArray_real_T(arg1,arg2);
}


SWIGEXPORT void SWIGSTDCALL CSharp_IsarMain_initialize() {
  IsarMain_initialize();
}


SWIGEXPORT void SWIGSTDCALL CSharp_IsarMain_terminate() {
  IsarMain_terminate();
}


#ifdef __cplusplus
}
#endif

