//------------------------------------------------------------------------------
// <auto-generated />
//
// This file was automatically generated by SWIG (http://www.swig.org).
// Version 3.0.12
//
// Do not make changes to this file unless you know what you are doing--modify
// the SWIG interface file instead.
//------------------------------------------------------------------------------


public class rtBoundsCheckInfo : global::System.IDisposable {
  private global::System.Runtime.InteropServices.HandleRef swigCPtr;
  protected bool swigCMemOwn;

  internal rtBoundsCheckInfo(global::System.IntPtr cPtr, bool cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = new global::System.Runtime.InteropServices.HandleRef(this, cPtr);
  }

  internal static global::System.Runtime.InteropServices.HandleRef getCPtr(rtBoundsCheckInfo obj) {
    return (obj == null) ? new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero) : obj.swigCPtr;
  }

  ~rtBoundsCheckInfo() {
    Dispose();
  }

  public virtual void Dispose() {
    lock(this) {
      if (swigCPtr.Handle != global::System.IntPtr.Zero) {
        if (swigCMemOwn) {
          swigCMemOwn = false;
          IsarMaincsPINVOKE.delete_rtBoundsCheckInfo(swigCPtr);
        }
        swigCPtr = new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero);
      }
      global::System.GC.SuppressFinalize(this);
    }
  }

  public SWIGTYPE_p_int32_T iFirst {
    set {
      IsarMaincsPINVOKE.rtBoundsCheckInfo_iFirst_set(swigCPtr, SWIGTYPE_p_int32_T.getCPtr(value));
      if (IsarMaincsPINVOKE.SWIGPendingException.Pending) throw IsarMaincsPINVOKE.SWIGPendingException.Retrieve();
    } 
    get {
      SWIGTYPE_p_int32_T ret = new SWIGTYPE_p_int32_T(IsarMaincsPINVOKE.rtBoundsCheckInfo_iFirst_get(swigCPtr), true);
      if (IsarMaincsPINVOKE.SWIGPendingException.Pending) throw IsarMaincsPINVOKE.SWIGPendingException.Retrieve();
      return ret;
    } 
  }

  public SWIGTYPE_p_int32_T iLast {
    set {
      IsarMaincsPINVOKE.rtBoundsCheckInfo_iLast_set(swigCPtr, SWIGTYPE_p_int32_T.getCPtr(value));
      if (IsarMaincsPINVOKE.SWIGPendingException.Pending) throw IsarMaincsPINVOKE.SWIGPendingException.Retrieve();
    } 
    get {
      SWIGTYPE_p_int32_T ret = new SWIGTYPE_p_int32_T(IsarMaincsPINVOKE.rtBoundsCheckInfo_iLast_get(swigCPtr), true);
      if (IsarMaincsPINVOKE.SWIGPendingException.Pending) throw IsarMaincsPINVOKE.SWIGPendingException.Retrieve();
      return ret;
    } 
  }

  public SWIGTYPE_p_int32_T lineNo {
    set {
      IsarMaincsPINVOKE.rtBoundsCheckInfo_lineNo_set(swigCPtr, SWIGTYPE_p_int32_T.getCPtr(value));
      if (IsarMaincsPINVOKE.SWIGPendingException.Pending) throw IsarMaincsPINVOKE.SWIGPendingException.Retrieve();
    } 
    get {
      SWIGTYPE_p_int32_T ret = new SWIGTYPE_p_int32_T(IsarMaincsPINVOKE.rtBoundsCheckInfo_lineNo_get(swigCPtr), true);
      if (IsarMaincsPINVOKE.SWIGPendingException.Pending) throw IsarMaincsPINVOKE.SWIGPendingException.Retrieve();
      return ret;
    } 
  }

  public SWIGTYPE_p_int32_T colNo {
    set {
      IsarMaincsPINVOKE.rtBoundsCheckInfo_colNo_set(swigCPtr, SWIGTYPE_p_int32_T.getCPtr(value));
      if (IsarMaincsPINVOKE.SWIGPendingException.Pending) throw IsarMaincsPINVOKE.SWIGPendingException.Retrieve();
    } 
    get {
      SWIGTYPE_p_int32_T ret = new SWIGTYPE_p_int32_T(IsarMaincsPINVOKE.rtBoundsCheckInfo_colNo_get(swigCPtr), true);
      if (IsarMaincsPINVOKE.SWIGPendingException.Pending) throw IsarMaincsPINVOKE.SWIGPendingException.Retrieve();
      return ret;
    } 
  }

  public string aName {
    set {
      IsarMaincsPINVOKE.rtBoundsCheckInfo_aName_set(swigCPtr, value);
    } 
    get {
      string ret = IsarMaincsPINVOKE.rtBoundsCheckInfo_aName_get(swigCPtr);
      return ret;
    } 
  }

  public string fName {
    set {
      IsarMaincsPINVOKE.rtBoundsCheckInfo_fName_set(swigCPtr, value);
    } 
    get {
      string ret = IsarMaincsPINVOKE.rtBoundsCheckInfo_fName_get(swigCPtr);
      return ret;
    } 
  }

  public string pName {
    set {
      IsarMaincsPINVOKE.rtBoundsCheckInfo_pName_set(swigCPtr, value);
    } 
    get {
      string ret = IsarMaincsPINVOKE.rtBoundsCheckInfo_pName_get(swigCPtr);
      return ret;
    } 
  }

  public SWIGTYPE_p_int32_T checkKind {
    set {
      IsarMaincsPINVOKE.rtBoundsCheckInfo_checkKind_set(swigCPtr, SWIGTYPE_p_int32_T.getCPtr(value));
      if (IsarMaincsPINVOKE.SWIGPendingException.Pending) throw IsarMaincsPINVOKE.SWIGPendingException.Retrieve();
    } 
    get {
      SWIGTYPE_p_int32_T ret = new SWIGTYPE_p_int32_T(IsarMaincsPINVOKE.rtBoundsCheckInfo_checkKind_get(swigCPtr), true);
      if (IsarMaincsPINVOKE.SWIGPendingException.Pending) throw IsarMaincsPINVOKE.SWIGPendingException.Retrieve();
      return ret;
    } 
  }

  public rtBoundsCheckInfo() : this(IsarMaincsPINVOKE.new_rtBoundsCheckInfo(), true) {
  }

}
