//------------------------------------------------------------------------------
// <auto-generated />
//
// This file was automatically generated by SWIG (http://www.swig.org).
// Version 3.0.12
//
// Do not make changes to this file unless you know what you are doing--modify
// the SWIG interface file instead.
//------------------------------------------------------------------------------


public class rtEqualityCheckInfo : global::System.IDisposable {
  private global::System.Runtime.InteropServices.HandleRef swigCPtr;
  protected bool swigCMemOwn;

  internal rtEqualityCheckInfo(global::System.IntPtr cPtr, bool cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = new global::System.Runtime.InteropServices.HandleRef(this, cPtr);
  }

  internal static global::System.Runtime.InteropServices.HandleRef getCPtr(rtEqualityCheckInfo obj) {
    return (obj == null) ? new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero) : obj.swigCPtr;
  }

  ~rtEqualityCheckInfo() {
    Dispose();
  }

  public virtual void Dispose() {
    lock(this) {
      if (swigCPtr.Handle != global::System.IntPtr.Zero) {
        if (swigCMemOwn) {
          swigCMemOwn = false;
          IsarMaincsPINVOKE.delete_rtEqualityCheckInfo(swigCPtr);
        }
        swigCPtr = new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero);
      }
      global::System.GC.SuppressFinalize(this);
    }
  }

  public SWIGTYPE_p_int32_T nDims {
    set {
      IsarMaincsPINVOKE.rtEqualityCheckInfo_nDims_set(swigCPtr, SWIGTYPE_p_int32_T.getCPtr(value));
      if (IsarMaincsPINVOKE.SWIGPendingException.Pending) throw IsarMaincsPINVOKE.SWIGPendingException.Retrieve();
    } 
    get {
      SWIGTYPE_p_int32_T ret = new SWIGTYPE_p_int32_T(IsarMaincsPINVOKE.rtEqualityCheckInfo_nDims_get(swigCPtr), true);
      if (IsarMaincsPINVOKE.SWIGPendingException.Pending) throw IsarMaincsPINVOKE.SWIGPendingException.Retrieve();
      return ret;
    } 
  }

  public SWIGTYPE_p_int32_T lineNo {
    set {
      IsarMaincsPINVOKE.rtEqualityCheckInfo_lineNo_set(swigCPtr, SWIGTYPE_p_int32_T.getCPtr(value));
      if (IsarMaincsPINVOKE.SWIGPendingException.Pending) throw IsarMaincsPINVOKE.SWIGPendingException.Retrieve();
    } 
    get {
      SWIGTYPE_p_int32_T ret = new SWIGTYPE_p_int32_T(IsarMaincsPINVOKE.rtEqualityCheckInfo_lineNo_get(swigCPtr), true);
      if (IsarMaincsPINVOKE.SWIGPendingException.Pending) throw IsarMaincsPINVOKE.SWIGPendingException.Retrieve();
      return ret;
    } 
  }

  public SWIGTYPE_p_int32_T colNo {
    set {
      IsarMaincsPINVOKE.rtEqualityCheckInfo_colNo_set(swigCPtr, SWIGTYPE_p_int32_T.getCPtr(value));
      if (IsarMaincsPINVOKE.SWIGPendingException.Pending) throw IsarMaincsPINVOKE.SWIGPendingException.Retrieve();
    } 
    get {
      SWIGTYPE_p_int32_T ret = new SWIGTYPE_p_int32_T(IsarMaincsPINVOKE.rtEqualityCheckInfo_colNo_get(swigCPtr), true);
      if (IsarMaincsPINVOKE.SWIGPendingException.Pending) throw IsarMaincsPINVOKE.SWIGPendingException.Retrieve();
      return ret;
    } 
  }

  public string fName {
    set {
      IsarMaincsPINVOKE.rtEqualityCheckInfo_fName_set(swigCPtr, value);
    } 
    get {
      string ret = IsarMaincsPINVOKE.rtEqualityCheckInfo_fName_get(swigCPtr);
      return ret;
    } 
  }

  public string pName {
    set {
      IsarMaincsPINVOKE.rtEqualityCheckInfo_pName_set(swigCPtr, value);
    } 
    get {
      string ret = IsarMaincsPINVOKE.rtEqualityCheckInfo_pName_get(swigCPtr);
      return ret;
    } 
  }

  public rtEqualityCheckInfo() : this(IsarMaincsPINVOKE.new_rtEqualityCheckInfo(), true) {
  }

}
