//------------------------------------------------------------------------------
// <auto-generated />
//
// This file was automatically generated by SWIG (http://www.swig.org).
// Version 3.0.12
//
// Do not make changes to this file unless you know what you are doing--modify
// the SWIG interface file instead.
//------------------------------------------------------------------------------


public class rtRunTimeErrorInfo : global::System.IDisposable {
  private global::System.Runtime.InteropServices.HandleRef swigCPtr;
  protected bool swigCMemOwn;

  internal rtRunTimeErrorInfo(global::System.IntPtr cPtr, bool cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = new global::System.Runtime.InteropServices.HandleRef(this, cPtr);
  }

  internal static global::System.Runtime.InteropServices.HandleRef getCPtr(rtRunTimeErrorInfo obj) {
    return (obj == null) ? new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero) : obj.swigCPtr;
  }

  ~rtRunTimeErrorInfo() {
    Dispose();
  }

  public virtual void Dispose() {
    lock(this) {
      if (swigCPtr.Handle != global::System.IntPtr.Zero) {
        if (swigCMemOwn) {
          swigCMemOwn = false;
          IsarMaincsPINVOKE.delete_rtRunTimeErrorInfo(swigCPtr);
        }
        swigCPtr = new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero);
      }
      global::System.GC.SuppressFinalize(this);
    }
  }

  public SWIGTYPE_p_int32_T lineNo {
    set {
      IsarMaincsPINVOKE.rtRunTimeErrorInfo_lineNo_set(swigCPtr, SWIGTYPE_p_int32_T.getCPtr(value));
      if (IsarMaincsPINVOKE.SWIGPendingException.Pending) throw IsarMaincsPINVOKE.SWIGPendingException.Retrieve();
    } 
    get {
      SWIGTYPE_p_int32_T ret = new SWIGTYPE_p_int32_T(IsarMaincsPINVOKE.rtRunTimeErrorInfo_lineNo_get(swigCPtr), true);
      if (IsarMaincsPINVOKE.SWIGPendingException.Pending) throw IsarMaincsPINVOKE.SWIGPendingException.Retrieve();
      return ret;
    } 
  }

  public SWIGTYPE_p_int32_T colNo {
    set {
      IsarMaincsPINVOKE.rtRunTimeErrorInfo_colNo_set(swigCPtr, SWIGTYPE_p_int32_T.getCPtr(value));
      if (IsarMaincsPINVOKE.SWIGPendingException.Pending) throw IsarMaincsPINVOKE.SWIGPendingException.Retrieve();
    } 
    get {
      SWIGTYPE_p_int32_T ret = new SWIGTYPE_p_int32_T(IsarMaincsPINVOKE.rtRunTimeErrorInfo_colNo_get(swigCPtr), true);
      if (IsarMaincsPINVOKE.SWIGPendingException.Pending) throw IsarMaincsPINVOKE.SWIGPendingException.Retrieve();
      return ret;
    } 
  }

  public string fName {
    set {
      IsarMaincsPINVOKE.rtRunTimeErrorInfo_fName_set(swigCPtr, value);
    } 
    get {
      string ret = IsarMaincsPINVOKE.rtRunTimeErrorInfo_fName_get(swigCPtr);
      return ret;
    } 
  }

  public string pName {
    set {
      IsarMaincsPINVOKE.rtRunTimeErrorInfo_pName_set(swigCPtr, value);
    } 
    get {
      string ret = IsarMaincsPINVOKE.rtRunTimeErrorInfo_pName_get(swigCPtr);
      return ret;
    } 
  }

  public rtRunTimeErrorInfo() : this(IsarMaincsPINVOKE.new_rtRunTimeErrorInfo(), true) {
  }

}
